"""SQLAlchemy record schema for durable PostgreSQL request delivery."""

import sqlalchemy
from sqlalchemy.dialects import postgresql

metadata = sqlalchemy.MetaData()
REQUESTS = sqlalchemy.Table(
    'api_requests',
    metadata,
    sqlalchemy.Column('request_id', sqlalchemy.Text, primary_key=True),
    sqlalchemy.Column('name', sqlalchemy.Text, nullable=False),
    sqlalchemy.Column('handler_name', sqlalchemy.Text, nullable=False),
    sqlalchemy.Column('payload_type', sqlalchemy.Text, nullable=False),
    sqlalchemy.Column('payload_format', sqlalchemy.Text, nullable=False),
    sqlalchemy.Column('payload_version', sqlalchemy.Integer, nullable=False),
    sqlalchemy.Column('producer_version', sqlalchemy.Text, nullable=False),
    sqlalchemy.Column('payload_json', postgresql.JSONB, nullable=False),
    sqlalchemy.Column('execution_class', sqlalchemy.Text, nullable=False),
    sqlalchemy.Column('status', sqlalchemy.Text, nullable=False),
    sqlalchemy.Column('return_value', postgresql.JSONB(none_as_null=True)),
    sqlalchemy.Column('error', postgresql.JSONB(none_as_null=True)),
    sqlalchemy.Column('pid', sqlalchemy.Integer),
    sqlalchemy.Column('created_at',
                      sqlalchemy.DateTime(timezone=True),
                      nullable=False),
    sqlalchemy.Column('cluster_name', sqlalchemy.Text),
    sqlalchemy.Column('schedule_type', sqlalchemy.Text, nullable=False),
    sqlalchemy.Column('user_id', sqlalchemy.Text, nullable=False),
    sqlalchemy.Column('status_msg', sqlalchemy.Text),
    sqlalchemy.Column('should_retry', sqlalchemy.Boolean, nullable=False),
    sqlalchemy.Column('finished_at', sqlalchemy.DateTime(timezone=True)),
    sqlalchemy.Column('file_mounts_blob_id', sqlalchemy.Text),
    sqlalchemy.Column('ignore_return_value', sqlalchemy.Boolean,
                      nullable=False),
    sqlalchemy.Column('retryable', sqlalchemy.Boolean, nullable=False),
    sqlalchemy.Column('execution_generation',
                      sqlalchemy.BigInteger,
                      nullable=False),
    sqlalchemy.Column('claim_token', postgresql.UUID(as_uuid=True)),
    sqlalchemy.Column('worker_instance_id', postgresql.UUID(as_uuid=True)),
    sqlalchemy.Column('controller_generation', sqlalchemy.BigInteger),
    sqlalchemy.Column('lease_expires_at', sqlalchemy.DateTime(timezone=True)),
    sqlalchemy.Column('heartbeat_at', sqlalchemy.DateTime(timezone=True)),
    sqlalchemy.Column('cancel_requested_at',
                      sqlalchemy.DateTime(timezone=True)),
    sqlalchemy.Column('cancel_acknowledged_at',
                      sqlalchemy.DateTime(timezone=True)),
    sqlalchemy.Column('interrupted_reason', sqlalchemy.Text),
    sqlalchemy.Column('event_context', postgresql.JSONB(none_as_null=True)),
    sqlalchemy.Column('resource_action_id', postgresql.UUID(as_uuid=True)),
    sqlalchemy.Column('resource_action_attempt', sqlalchemy.Integer),
    sqlalchemy.Column('updated_at',
                      sqlalchemy.DateTime(timezone=True),
                      nullable=False),
)
RESOURCE_ACTIONS = sqlalchemy.Table(
    'api_resource_actions',
    metadata,
    sqlalchemy.Column('action_id',
                      postgresql.UUID(as_uuid=True),
                      primary_key=True),
    sqlalchemy.Column('domain', sqlalchemy.Text, nullable=False),
    sqlalchemy.Column('resource_type', sqlalchemy.Text, nullable=False),
    sqlalchemy.Column('resource_identity', sqlalchemy.Text, nullable=False),
    sqlalchemy.Column('desired_generation',
                      sqlalchemy.BigInteger,
                      nullable=False),
    sqlalchemy.Column('action_type', sqlalchemy.Text, nullable=False),
    sqlalchemy.Column('immutable_spec',
                      postgresql.JSONB(none_as_null=True),
                      nullable=False),
    sqlalchemy.Column('immutable_spec_sha256', sqlalchemy.Text, nullable=False),
    sqlalchemy.Column('kernel_state', sqlalchemy.Text, nullable=False),
    sqlalchemy.Column('current_attempt', sqlalchemy.Integer, nullable=False),
    sqlalchemy.Column('next_attempt_at', sqlalchemy.DateTime(timezone=True)),
    sqlalchemy.Column('last_result', postgresql.JSONB(none_as_null=True)),
    sqlalchemy.Column('last_result_sha256', sqlalchemy.Text),
    sqlalchemy.Column('terminal_disposition', sqlalchemy.Text),
    sqlalchemy.Column('revision', sqlalchemy.BigInteger, nullable=False),
    sqlalchemy.Column('created_at',
                      sqlalchemy.DateTime(timezone=True),
                      nullable=False),
    sqlalchemy.Column('updated_at',
                      sqlalchemy.DateTime(timezone=True),
                      nullable=False),
    sqlalchemy.Column('terminal_at', sqlalchemy.DateTime(timezone=True)),
)
RESOURCE_ACTION_ATTEMPTS = sqlalchemy.Table(
    'api_resource_action_attempts',
    metadata,
    sqlalchemy.Column('action_id',
                      postgresql.UUID(as_uuid=True),
                      primary_key=True),
    sqlalchemy.Column('attempt', sqlalchemy.Integer, primary_key=True),
    sqlalchemy.Column('request_id', sqlalchemy.Text, nullable=False),
    sqlalchemy.Column('request_input_sha256', sqlalchemy.Text, nullable=False),
    sqlalchemy.Column('provider_operation_id', sqlalchemy.Text),
    sqlalchemy.Column('mutation_boundary', sqlalchemy.Text, nullable=False),
    sqlalchemy.Column('provider_io_boundary',
                      sqlalchemy.Text,
                      nullable=False,
                      server_default='NOT_STARTED'),
    sqlalchemy.Column('provider_progress', postgresql.JSONB(none_as_null=True)),
    sqlalchemy.Column('provider_progress_sha256', sqlalchemy.Text),
    sqlalchemy.Column('provider_progress_revision',
                      sqlalchemy.BigInteger,
                      nullable=False,
                      server_default='0'),
    sqlalchemy.Column('typed_outcome', postgresql.JSONB(none_as_null=True)),
    sqlalchemy.Column('typed_outcome_sha256', sqlalchemy.Text),
    sqlalchemy.Column('request_terminal_state', sqlalchemy.Text),
    sqlalchemy.Column('admitted_at',
                      sqlalchemy.DateTime(timezone=True),
                      nullable=False),
    sqlalchemy.Column('updated_at',
                      sqlalchemy.DateTime(timezone=True),
                      nullable=False),
    sqlalchemy.Column('settled_at', sqlalchemy.DateTime(timezone=True)),
)
QUEUE = sqlalchemy.Table(
    'api_request_queue',
    metadata,
    sqlalchemy.Column('request_id', sqlalchemy.Text, primary_key=True),
    sqlalchemy.Column('schedule_type', sqlalchemy.Text, nullable=False),
    sqlalchemy.Column('priority', sqlalchemy.Integer, nullable=False),
    sqlalchemy.Column('available_at',
                      sqlalchemy.DateTime(timezone=True),
                      nullable=False),
    sqlalchemy.Column('enqueued_at',
                      sqlalchemy.DateTime(timezone=True),
                      nullable=False),
    sqlalchemy.Column('sequence',
                      sqlalchemy.BigInteger,
                      sqlalchemy.Identity(),
                      nullable=False,
                      unique=True),
    sqlalchemy.Column('ignore_return_value', sqlalchemy.Boolean,
                      nullable=False),
    sqlalchemy.Column('retryable', sqlalchemy.Boolean, nullable=False),
    sqlalchemy.Column('precondition_type', sqlalchemy.Text),
    sqlalchemy.Column('precondition_payload',
                      postgresql.JSONB(none_as_null=True)),
    sqlalchemy.Column('precondition_deadline',
                      sqlalchemy.DateTime(timezone=True)),
    sqlalchemy.Column('precondition_attempts',
                      sqlalchemy.BigInteger,
                      nullable=False),
    sqlalchemy.Column('delivery_state', sqlalchemy.Text, nullable=False),
    sqlalchemy.Column('claim_generation', sqlalchemy.BigInteger),
    sqlalchemy.Column('updated_at',
                      sqlalchemy.DateTime(timezone=True),
                      nullable=False),
)
STORE_METADATA = sqlalchemy.Table(
    'api_request_store_metadata',
    metadata,
    sqlalchemy.Column('key', sqlalchemy.Text, primary_key=True),
    sqlalchemy.Column('value', postgresql.JSONB, nullable=False),
    sqlalchemy.Column('updated_at',
                      sqlalchemy.DateTime(timezone=True),
                      nullable=False),
)
SERVER_INSTANCES = sqlalchemy.Table(
    'api_server_instances',
    metadata,
    sqlalchemy.Column('instance_id',
                      postgresql.UUID(as_uuid=True),
                      primary_key=True),
    sqlalchemy.Column('role', sqlalchemy.Text, nullable=False),
    sqlalchemy.Column('pod_name', sqlalchemy.Text),
    sqlalchemy.Column('pod_uid', sqlalchemy.Text),
    sqlalchemy.Column('pod_ip', sqlalchemy.Text),
    sqlalchemy.Column('version', sqlalchemy.Text, nullable=False),
    sqlalchemy.Column('started_at',
                      sqlalchemy.DateTime(timezone=True),
                      nullable=False),
    sqlalchemy.Column('heartbeat_at',
                      sqlalchemy.DateTime(timezone=True),
                      nullable=False),
    sqlalchemy.Column('draining_at', sqlalchemy.DateTime(timezone=True)),
    sqlalchemy.Column('ready', sqlalchemy.Boolean, nullable=False),
    sqlalchemy.Column('health_detail',
                      postgresql.JSONB(none_as_null=True),
                      nullable=False),
    sqlalchemy.Column('supported_handlers',
                      postgresql.JSONB(none_as_null=True),
                      nullable=False),
    sqlalchemy.Column('supported_payload_versions',
                      postgresql.JSONB(none_as_null=True),
                      nullable=False),
)
CONTROLLER_LEADERSHIP = sqlalchemy.Table(
    'api_controller_leadership',
    metadata,
    sqlalchemy.Column('leadership_key', sqlalchemy.Text, primary_key=True),
    sqlalchemy.Column('generation', sqlalchemy.BigInteger, nullable=False),
    sqlalchemy.Column('instance_id',
                      postgresql.UUID(as_uuid=True),
                      nullable=False),
    sqlalchemy.Column('lock_backend_pid', sqlalchemy.Integer, nullable=False),
    sqlalchemy.Column('generation_lock_key',
                      sqlalchemy.BigInteger,
                      nullable=False),
    sqlalchemy.Column('acquired_at',
                      sqlalchemy.DateTime(timezone=True),
                      nullable=False),
    sqlalchemy.Column('heartbeat_at',
                      sqlalchemy.DateTime(timezone=True),
                      nullable=False),
    sqlalchemy.Column('released_at', sqlalchemy.DateTime(timezone=True)),
)
CONTROLLER_ACTION_RESERVATIONS = sqlalchemy.Table(
    'api_controller_action_reservations',
    metadata,
    sqlalchemy.Column('logical_action_id', sqlalchemy.Text, primary_key=True),
    sqlalchemy.Column('resource_identity', sqlalchemy.Text, nullable=False),
    sqlalchemy.Column('action_type', sqlalchemy.Text, nullable=False),
    sqlalchemy.Column('state', sqlalchemy.Text, nullable=False),
    sqlalchemy.Column('controller_generation',
                      sqlalchemy.BigInteger,
                      nullable=False),
    sqlalchemy.Column('controller_instance_id',
                      postgresql.UUID(as_uuid=True),
                      nullable=False),
    sqlalchemy.Column('provider_operation_id', sqlalchemy.Text),
    sqlalchemy.Column('created_at',
                      sqlalchemy.DateTime(timezone=True),
                      nullable=False),
    sqlalchemy.Column('updated_at',
                      sqlalchemy.DateTime(timezone=True),
                      nullable=False),
    sqlalchemy.Column('reconciliation_at', sqlalchemy.DateTime(timezone=True)),
)
PG_LOCKS = sqlalchemy.table(
    'pg_locks',
    sqlalchemy.column('locktype', sqlalchemy.Text),
    sqlalchemy.column('pid', sqlalchemy.Integer),
    sqlalchemy.column('classid'),
    sqlalchemy.column('objid'),
    sqlalchemy.column('objsubid', sqlalchemy.Integer),
    sqlalchemy.column('mode', sqlalchemy.Text),
    sqlalchemy.column('granted', sqlalchemy.Boolean),
    schema='pg_catalog',
)
