"""Stub file for sky.utils.command_runner.

This file is dynamically generated by stubgen and added with the
overloaded type hints for SSHCommandRunner.run(), as we need to
determine the return type based on the value of require_outputs.
"""
from collections.abc import Callable
from collections.abc import Iterable
import enum
import typing
from typing import Any, Literal

from sky import sky_logging as sky_logging
from sky.skylet import log_lib as log_lib
from sky.utils import subprocess_utils as subprocess_utils

GIT_EXCLUDE: str
RSYNC_DISPLAY_OPTION: str
RSYNC_FILTER_GITIGNORE: str
RSYNC_FILTER_SKYIGNORE: str
RSYNC_EXCLUDE_OPTION: str
ALIAS_SUDO_TO_EMPTY_FOR_ROOT_CMD: str
DEFAULT_SSH_CONTROL_NAME: str


def ssh_options_list(
    ssh_private_key: str | None,
    ssh_control_name: str | None,
    *,
    ssh_proxy_command: str | None = ...,
    ssh_proxy_jump: str | None = ...,
    docker_ssh_proxy_command: str | None = ...,
    connect_timeout: int | None = ...,
    port: int = ...,
    disable_control_master: bool | None = ...,
    escape_percent_expand: bool = ...,
    ssh_log_file: str | None = ...,
    disable_identities_only: bool = ...,
) -> list[str]:
    ...


class SshMode(enum.Enum):
    NON_INTERACTIVE = ...
    INTERACTIVE = ...
    LOGIN = ...


class CommandRunner:

    def __init__(
        self,
        node: tuple[Any, ...],
        **kwargs,
    ) -> None:
        ...

    @property
    def node_id(self) -> str:
        ...

    @typing.overload
    def run(self,
            cmd: str | list[str],
            *,
            require_outputs: Literal[False] = ...,
            log_path: str = ...,
            process_stream: bool = ...,
            stream_logs: bool = ...,
            ssh_mode: SshMode = ...,
            separate_stderr: bool = ...,
            connect_timeout: int | None = ...,
            source_bashrc: bool = ...,
            skip_num_lines: int = ...,
            run_in_background: bool = ...,
            **kwargs) -> int:
        ...

    @typing.overload
    def run(self,
            cmd: str | list[str],
            *,
            require_outputs: Literal[True],
            log_path: str = ...,
            process_stream: bool = ...,
            stream_logs: bool = ...,
            ssh_mode: SshMode = ...,
            separate_stderr: bool = ...,
            connect_timeout: int | None = ...,
            source_bashrc: bool = ...,
            skip_num_lines: int = ...,
            run_in_background: bool = ...,
            **kwargs) -> tuple[int, str, str]:
        ...

    @typing.overload
    def run(self,
            cmd: str | list[str],
            *,
            require_outputs: bool = ...,
            log_path: str = ...,
            process_stream: bool = ...,
            stream_logs: bool = ...,
            ssh_mode: SshMode = ...,
            separate_stderr: bool = ...,
            connect_timeout: int | None = ...,
            source_bashrc: bool = ...,
            skip_num_lines: int = ...,
            run_in_background: bool = ...,
            **kwargs) -> tuple[int, str, str] | int:
        ...

    def get_remote_home_dir(self) -> str:
        ...

    def rsync(
        self,
        source: str,
        target: str,
        *,
        up: bool,
        log_path: str = ...,
        stream_logs: bool = ...,
        max_retry: int = ...,
        timeout: int | None = ...,
    ) -> None:
        ...

    @typing.overload
    def run_driver(self,
                   cmd: str | list[str],
                   *,
                   require_outputs: Literal[False] = ...,
                   **kwargs) -> int:
        ...

    @typing.overload
    def run_driver(self, cmd: str | list[str], *,
                   require_outputs: Literal[True],
                   **kwargs) -> tuple[int, str, str]:
        ...

    @typing.overload
    def run_driver(self,
                   cmd: str | list[str],
                   *,
                   require_outputs: bool = ...,
                   **kwargs) -> tuple[int, str, str] | int:
        ...

    @typing.overload
    def run_setup(self,
                  cmd: str | list[str],
                  *,
                  require_outputs: Literal[False] = ...,
                  **kwargs) -> int:
        ...

    @typing.overload
    def run_setup(self, cmd: str | list[str], *, require_outputs: Literal[True],
                  **kwargs) -> tuple[int, str, str]:
        ...

    @typing.overload
    def run_setup(self,
                  cmd: str | list[str],
                  *,
                  require_outputs: bool = ...,
                  **kwargs) -> tuple[int, str, str] | int:
        ...

    def rsync_driver(self,
                     source: str,
                     target: str,
                     *,
                     up: bool,
                     log_path: str = ...,
                     stream_logs: bool = ...,
                     max_retry: int = ...,
                     timeout: int | None = ...) -> None:
        ...

    def rsync_setup(self,
                    source: str,
                    target: str,
                    *,
                    up: bool,
                    log_path: str = ...,
                    stream_logs: bool = ...,
                    max_retry: int = ...,
                    timeout: int | None = ...) -> None:
        ...

    def port_forward_command(
            self,
            port_forward: list[tuple[int, int]],
            connect_timeout: int = 1,
            ssh_mode: SshMode = SshMode.INTERACTIVE) -> list[str]:
        ...

    @classmethod
    def make_runner_list(cls: type[CommandRunner],
                         node_list: Iterable[tuple[Any, ...]],
                         **kwargs) -> list[CommandRunner]:
        ...

    def check_connection(self) -> bool:
        ...

    def close_cached_connection(self) -> None:
        ...


class SSHCommandRunner(CommandRunner):
    ip: str
    port: int
    ssh_user: str
    ssh_private_key: str | None
    ssh_control_name: str | None
    docker_user: str
    disable_control_master: bool | None
    port_forward_execute_remote_command: bool | None
    enable_interactive_auth: bool
    disable_identities_only: bool

    def __init__(
        self,
        node: tuple[str, int],
        ssh_user: str,
        ssh_private_key: str | None,
        ssh_control_name: str | None = ...,
        ssh_proxy_command: str | None = ...,
        ssh_proxy_jump: str | None = ...,
        docker_user: str | None = ...,
        disable_control_master: bool | None = ...,
        port_forward_execute_remote_command: bool | None = ...,
        enable_interactive_auth: bool = ...,
        disable_identities_only: bool = ...,
    ) -> None:
        ...

    @typing.overload
    def run(self,
            cmd: str | list[str],
            *,
            require_outputs: Literal[False] = ...,
            port_forward: list[tuple[int, int]] | None = ...,
            log_path: str = ...,
            process_stream: bool = ...,
            stream_logs: bool = ...,
            ssh_mode: SshMode = ...,
            separate_stderr: bool = ...,
            connect_timeout: int | None = ...,
            source_bashrc: bool = ...,
            skip_num_lines: int = ...,
            run_in_background: bool = ...,
            **kwargs) -> int:
        ...

    @typing.overload
    def run(self,
            cmd: str | list[str],
            *,
            require_outputs: Literal[True],
            port_forward: list[tuple[int, int]] | None = ...,
            log_path: str = ...,
            process_stream: bool = ...,
            stream_logs: bool = ...,
            ssh_mode: SshMode = ...,
            separate_stderr: bool = ...,
            connect_timeout: int | None = ...,
            source_bashrc: bool = ...,
            skip_num_lines: int = ...,
            run_in_background: bool = ...,
            **kwargs) -> tuple[int, str, str]:
        ...

    @typing.overload
    def run(self,
            cmd: str | list[str],
            *,
            require_outputs: bool = ...,
            port_forward: list[tuple[int, int]] | None = ...,
            log_path: str = ...,
            process_stream: bool = ...,
            stream_logs: bool = ...,
            ssh_mode: SshMode = ...,
            separate_stderr: bool = ...,
            connect_timeout: int | None = ...,
            source_bashrc: bool = ...,
            skip_num_lines: int = ...,
            run_in_background: bool = ...,
            **kwargs) -> tuple[int, str, str] | int:
        ...

    def ssh_base_command(
        self,
        *,
        ssh_mode: SshMode,
        port_forward: list[tuple[int, int]] | None,
        connect_timeout: int | None,
        ssh_log_file: str | None = ...,
    ) -> list[str]:
        ...

    def rsync(
        self,
        source: str,
        target: str,
        *,
        up: bool,
        log_path: str = ...,
        stream_logs: bool = ...,
        max_retry: int = ...,
        get_remote_home_dir: Callable[[], str] = ...,
        timeout: int | None = ...,
    ) -> None:
        ...

    def port_forward_command(
            self,
            port_forward: list[tuple[int, int]],
            connect_timeout: int = 1,
            ssh_mode: SshMode = SshMode.INTERACTIVE) -> list[str]:
        ...

    def note_transport_failure(self, returncode: int) -> bool:
        ...


class KubernetesCommandRunner(CommandRunner):

    def __init__(
        self,
        node: tuple[tuple[str, str | None], str],
        deployment: str | None = ...,
        container: str | None = ...,
        **kwargs,
    ) -> None:
        ...

    @typing.overload
    def run(self,
            cmd: str | list[str],
            *,
            port_forward: list[int] | None = ...,
            require_outputs: Literal[False] = ...,
            log_path: str = ...,
            process_stream: bool = ...,
            stream_logs: bool = ...,
            ssh_mode: SshMode = ...,
            separate_stderr: bool = ...,
            connect_timeout: int | None = ...,
            source_bashrc: bool = ...,
            skip_num_lines: int = ...,
            run_in_background: bool = ...,
            **kwargs) -> int:
        ...

    @typing.overload
    def run(self,
            cmd: str | list[str],
            *,
            port_forward: list[int] | None = ...,
            require_outputs: Literal[True],
            log_path: str = ...,
            process_stream: bool = ...,
            stream_logs: bool = ...,
            ssh_mode: SshMode = ...,
            separate_stderr: bool = ...,
            connect_timeout: int | None = ...,
            source_bashrc: bool = ...,
            skip_num_lines: int = ...,
            run_in_background: bool = ...,
            **kwargs) -> tuple[int, str, str]:
        ...

    @typing.overload
    def run(self,
            cmd: str | list[str],
            *,
            port_forward: list[int] | None = ...,
            require_outputs: bool = ...,
            log_path: str = ...,
            process_stream: bool = ...,
            stream_logs: bool = ...,
            ssh_mode: SshMode = ...,
            separate_stderr: bool = ...,
            connect_timeout: int | None = ...,
            source_bashrc: bool = ...,
            skip_num_lines: int = ...,
            run_in_background: bool = ...,
            **kwargs) -> tuple[int, str, str] | int:
        ...

    def rsync(
        self,
        source: str,
        target: str,
        *,
        up: bool,
        log_path: str = ...,
        stream_logs: bool = ...,
        max_retry: int = ...,
        timeout: int | None = ...,
    ) -> None:
        ...

    def port_forward_command(
            self,
            port_forward: list[tuple[int, int]],
            connect_timeout: int = 1,
            ssh_mode: SshMode = SshMode.INTERACTIVE) -> list[str]:
        ...


class SlurmCommandRunner(SSHCommandRunner):
    """Runner for Slurm commands."""
    sky_dir: str
    skypilot_runtime_dir: str
    job_id: str
    slurm_node: str
    container_args: str | None

    def __init__(
        self,
        node: tuple[str, int],
        ssh_user: str,
        ssh_private_key: str | None,
        *,
        sky_dir: str,
        skypilot_runtime_dir: str,
        job_id: str,
        slurm_node: str,
        container_args: str | None,
        **kwargs,
    ) -> None:
        ...

    def rsync(
        self,
        source: str,
        target: str,
        *,
        up: bool,
        log_path: str = ...,
        stream_logs: bool = ...,
        max_retry: int = ...,
        get_remote_home_dir: Callable[[], str] | None = ...,
        timeout: int | None = ...,
    ) -> None:
        ...


class LocalProcessCommandRunner(CommandRunner):

    def __init__(self) -> None:
        ...

    @typing.overload
    def run(self,
            cmd: str | list[str],
            *,
            port_forward: list[tuple[int, int]] | None = ...,
            require_outputs: Literal[False] = ...,
            log_path: str = ...,
            process_stream: bool = ...,
            stream_logs: bool = ...,
            ssh_mode: SshMode = ...,
            separate_stderr: bool = ...,
            connect_timeout: int | None = ...,
            source_bashrc: bool = ...,
            skip_num_lines: int = ...,
            run_in_background: bool = ...,
            **kwargs) -> int:
        ...

    @typing.overload
    def run(self,
            cmd: str | list[str],
            *,
            port_forward: list[tuple[int, int]] | None = ...,
            require_outputs: Literal[True],
            log_path: str = ...,
            process_stream: bool = ...,
            stream_logs: bool = ...,
            ssh_mode: SshMode = ...,
            separate_stderr: bool = ...,
            connect_timeout: int | None = ...,
            source_bashrc: bool = ...,
            skip_num_lines: int = ...,
            run_in_background: bool = ...,
            **kwargs) -> tuple[int, str, str]:
        ...

    @typing.overload
    def run(self,
            cmd: str | list[str],
            *,
            port_forward: list[tuple[int, int]] | None = ...,
            require_outputs: bool = ...,
            log_path: str = ...,
            process_stream: bool = ...,
            stream_logs: bool = ...,
            ssh_mode: SshMode = ...,
            separate_stderr: bool = ...,
            connect_timeout: int | None = ...,
            source_bashrc: bool = ...,
            skip_num_lines: int = ...,
            run_in_background: bool = ...,
            **kwargs) -> tuple[int, str, str] | int:
        ...
