"""Type stubs for log_lib.py.
This file is dynamically generated by stubgen and added with the
overloaded type hints for run_with_log(), as we need to determine
the return type based on the value of require_outputs.
"""
from collections.abc import Iterable
from collections.abc import Iterator
import typing
from typing import Literal

from sky import sky_logging as sky_logging
from sky.skylet import constants as constants
from sky.skylet import job_lib as job_lib
from sky.skylet import system_oom_recovery as system_oom_recovery
from sky.utils import context
from sky.utils import log_utils as log_utils

SKY_LOG_WAITING_GAP_SECONDS: int = ...
SKY_LOG_WAITING_MAX_RETRY: int = ...
SKY_LOG_TAILING_GAP_SECONDS: float = ...
LOG_FILE_START_STREAMING_AT: str = ...


class BoundedSubprocessCapture:
    """Finite POSIX capture contract for short control-plane commands."""

    deadline_monotonic: int | float
    max_output_bytes: int

    def __init__(self, *, deadline_monotonic: int | float,
                 max_output_bytes: int) -> None:
        ...


class SubprocessOutputLimitExceeded(RuntimeError):
    ...


class _ProcessingArgs:
    log_path: str
    stream_logs: bool
    start_streaming_at: str = ...
    end_streaming_at: str | None = ...
    skip_lines: list[str] | None = ...
    replace_crlf: bool = ...
    line_processor: log_utils.LineProcessor | None = ...
    streaming_prefix: str | None = ...

    def __init__(self,
                 log_path: str,
                 stream_logs: bool,
                 start_streaming_at: str = ...,
                 end_streaming_at: str | None = ...,
                 skip_lines: list[str] | None = ...,
                 replace_crlf: bool = ...,
                 line_processor: log_utils.LineProcessor | None = ...,
                 streaming_prefix: str | None = ...) -> None:
        ...


def _get_context() -> context.SkyPilotContext | None:
    ...


def _handle_io_stream(io_stream, out_stream, args: _ProcessingArgs):
    ...


def process_subprocess_stream(proc, stdout_stream_handler,
                              stderr_stream_handler) -> tuple[str, str]:
    ...


@typing.overload
def run_with_log(cmd: list[str] | str,
                 log_path: str,
                 *,
                 require_outputs: Literal[False] = False,
                 stream_logs: bool = ...,
                 start_streaming_at: str = ...,
                 end_streaming_at: str | None = ...,
                 skip_lines: list[str] | None = ...,
                 shell: bool = ...,
                 with_ray: bool = ...,
                 process_stream: bool = ...,
                 line_processor: log_utils.LineProcessor | None = ...,
                 streaming_prefix: str | None = ...,
                 log_cmd: bool = ...,
                 timeout: int | None = ...,
                 bounded_capture: BoundedSubprocessCapture | None = ...,
                 **kwargs) -> int:
    ...


@typing.overload
def run_with_log(cmd: list[str] | str,
                 log_path: str,
                 *,
                 require_outputs: Literal[True],
                 stream_logs: bool = ...,
                 start_streaming_at: str = ...,
                 end_streaming_at: str | None = ...,
                 skip_lines: list[str] | None = ...,
                 shell: bool = ...,
                 with_ray: bool = ...,
                 process_stream: bool = ...,
                 line_processor: log_utils.LineProcessor | None = ...,
                 streaming_prefix: str | None = ...,
                 log_cmd: bool = ...,
                 timeout: int | None = ...,
                 bounded_capture: BoundedSubprocessCapture | None = ...,
                 **kwargs) -> tuple[int, str, str]:
    ...


@typing.overload
def run_with_log(cmd: list[str] | str,
                 log_path: str,
                 *,
                 require_outputs: bool,
                 stream_logs: bool = ...,
                 start_streaming_at: str = ...,
                 end_streaming_at: str | None = ...,
                 skip_lines: list[str] | None = ...,
                 shell: bool = ...,
                 with_ray: bool = ...,
                 process_stream: bool = ...,
                 line_processor: log_utils.LineProcessor | None = ...,
                 streaming_prefix: str | None = ...,
                 log_cmd: bool = ...,
                 timeout: int | None = ...,
                 bounded_capture: BoundedSubprocessCapture | None = ...,
                 **kwargs) -> int | tuple[int, str, str]:
    ...


def make_task_bash_script(codegen: str,
                          env_vars: dict[str, str] | None = ...) -> str:
    ...


def add_ray_env_vars(env_vars: dict[str, str] | None = ...) -> dict[str, str]:
    ...


def run_bash_command_with_log(bash_command: str,
                              log_path: str,
                              env_vars: dict[str, str] | None = ...,
                              stream_logs: bool = ...,
                              with_ray: bool = ...,
                              streaming_prefix: str | None = ...) -> int:
    ...


def run_bash_command_with_log_and_return_pid(
        bash_command: str,
        log_path: str,
        env_vars: dict[str, str] | None = ...,
        stream_logs: bool = ...,
        with_ray: bool = ...,
        streaming_prefix: str | None = ...) -> dict[str, int | str]:
    ...


def run_bash_command_with_log_and_return_pid_with_system_oom_recovery(
        log_path: str,
        recovery_context: dict[str, object],
        recovery_plan: system_oom_recovery.RecoveryLaunchPlan,
        env_vars: dict[str, str] | None = ...,
        stream_logs: bool = ...,
        with_ray: bool = ...,
        streaming_prefix: str | None = ...) -> dict[str, int | str]:
    ...


def tail_lines_from_end(path: str,
                        tail: int,
                        offset: int = ...) -> tuple[list[str], int]:
    ...


def tail_logs(job_id: int,
              log_dir: str | None,
              managed_job_id: int | None = ...,
              follow: bool = ...,
              tail: int = ...,
              tail_offset: int = ...) -> None:
    ...


def tail_logs_iter(job_id: int | None,
                   log_dir: str | None,
                   managed_job_id: int | None = ...,
                   follow: bool = ...,
                   tail: int = ...,
                   tail_offset: int = ...) -> Iterator[str]:
    ...


class LogBuffer:
    max_chars: int

    def __init__(self, max_chars: int = ...):
        ...

    def flush(self) -> str:
        ...

    def write(self, line: str) -> bool:
        ...

    def close(self):
        ...


def buffered_iter_with_timeout(buffer: LogBuffer, iterable: Iterable[str],
                               timeout: float) -> Iterable[str]:
    ...
