"""Dashboard presentation routes and middleware for the API server."""

import json
import os
import pathlib
import posixpath
import re

import fastapi
import starlette.middleware.base

from sky import sky_logging
from sky.server import constants as server_constants
from sky.server import csp_utils
from sky.server.file_mount_uploads import is_relative_to as _is_relative_to

logger = sky_logging.init_logger('sky.server.server')

router = fastapi.APIRouter()


# Add a new middleware class to handle /internal/dashboard prefix
class InternalDashboardPrefixMiddleware(
        starlette.middleware.base.BaseHTTPMiddleware):
    """Middleware to handle /internal/dashboard prefix in requests."""

    async def dispatch(self, request: fastapi.Request, call_next):
        path = request.url.path
        if path.startswith('/internal/dashboard/'):
            # Remove /internal/dashboard prefix and update request scope
            request.scope['path'] = path.replace('/internal/dashboard/', '/', 1)
        return await call_next(request)


class CacheControlStaticMiddleware(starlette.middleware.base.BaseHTTPMiddleware
                                  ):
    """Middleware to add cache control headers to static files."""

    async def dispatch(self, request: fastapi.Request, call_next):
        if request.url.path.startswith('/dashboard/_next'):
            response = await call_next(request)
            # Respect an explicit Cache-Control set by downstream middleware
            # or handlers (e.g. an auth middleware that set 'no-store' on a
            # 401). Otherwise, fall back to the static-asset defaults.
            if 'Cache-Control' not in response.headers:
                if response.status_code >= 400:
                    # Error responses (e.g. 401 from an auth middleware) must
                    # not be cached: a CDN that caches them for the same path
                    # will serve the error to all subsequent users until the
                    # cache entry expires, breaking the dashboard for
                    # everyone.
                    response.headers['Cache-Control'] = 'no-store'
                else:
                    response.headers['Cache-Control'] = 'max-age=3600'
            return response
        return await call_next(request)


class PathCleanMiddleware(starlette.middleware.base.BaseHTTPMiddleware):
    """Middleware to check the path of requests."""

    async def dispatch(self, request: fastapi.Request, call_next):
        if request.url.path.startswith('/dashboard/'):
            # If the requested path is not relative to the expected directory,
            # then the user is attempting path traversal, so deny the request.
            parent = pathlib.Path('/dashboard')
            request_path = pathlib.Path(posixpath.normpath(request.url.path))
            if not _is_relative_to(request_path, parent):
                return fastapi.responses.JSONResponse(
                    status_code=403, content={'detail': 'Forbidden'})
        return await call_next(request)


def _load_dynamic_routes() -> list[tuple['re.Pattern[str]', str]]:
    """Load dynamic route patterns from the Next.js routes manifest.

    Returns a list of ``(compiled_regex, page_path)`` tuples parsed from the
    ``routes-manifest.json`` file generated by ``next build``.  The manifest is
    read once and cached for the lifetime of the process.
    """
    manifest_path = os.path.join(server_constants.DASHBOARD_DIR,
                                 'routes-manifest.json')
    try:
        with open(manifest_path, encoding='utf-8') as f:
            manifest = json.load(f)
        return [(re.compile(r['regex']), r['page'])
                for r in manifest.get('dynamicRoutes', [])]
    except (OSError, json.JSONDecodeError, KeyError) as e:
        logger.warning(f'Failed to load routes manifest: {e}')
        return []


# Cached dynamic routes loaded from the Next.js routes manifest.
_DYNAMIC_ROUTES: list[tuple['re.Pattern[str]', str]] | None = None


def _get_dynamic_routes() -> list[tuple['re.Pattern[str]', str]]:
    """Return the cached dynamic routes, loading them on first call."""
    global _DYNAMIC_ROUTES
    if _DYNAMIC_ROUTES is None:
        _DYNAMIC_ROUTES = _load_dynamic_routes()
    return _DYNAMIC_ROUTES


def _resolve_dynamic_route(dashboard_dir: str, path: str) -> str | None:
    """Resolve a URL path to a Next.js dynamic-route HTML file.

    Uses the ``routes-manifest.json`` generated by ``next build`` to match
    the *path* against pre-compiled dynamic route regexes.  The manifest
    already orders routes from most-specific to least-specific (catch-all
    routes come last), so the first match wins.

    Args:
        dashboard_dir: Absolute path to the dashboard ``out/`` directory.
        path: URL path without leading slash,
            e.g. ``clusters/my-cluster``.

    Returns:
        Absolute path to the matching HTML file, or ``None``.
    """
    for pattern, page in _get_dynamic_routes():
        if pattern.match('/' + path):
            html_file = page.lstrip('/') + '.html'
            html_path = os.path.join(dashboard_dir, html_file)
            if os.path.isfile(html_path):
                return html_path
    return None


def _serve_html_with_nonce(
    request: fastapi.Request,
    file_path: str,
) -> fastapi.responses.HTMLResponse:
    """Read an HTML file, inject a CSP nonce, and return as HTMLResponse.

    The nonce is also stored in ``request.state.csp_nonce`` so that
    :class:`SecurityHeadersMiddleware` can reference it in the CSP header.
    """
    nonce = csp_utils.generate_nonce()
    request.state.csp_nonce = nonce

    with open(file_path, encoding='utf-8') as f:
        content = f.read()

    content = csp_utils.inject_nonce_into_html(content, nonce)
    return fastapi.responses.HTMLResponse(content=content)


@router.get('/dashboard/{full_path:path}')
async def serve_dashboard(request: fastapi.Request, full_path: str):
    """Serves the Next.js dashboard application.

    Args:
        request: The incoming HTTP request (used to attach the CSP nonce).
        full_path: The path requested by the client.
        e.g. /clusters, /jobs

    Returns:
        FileResponse for static files, or nonce-injected HTMLResponse for
        HTML pages.

    Raises:
        HTTPException: If the path is invalid or file not found.
    """
    # Reject path traversal attempts before any filesystem access.
    safe_full_path = full_path.lstrip('/')
    if '..' in safe_full_path.split('/'):
        raise fastapi.HTTPException(status_code=400, detail='Invalid path')

    # Try to serve the static file directly e.g. /skypilot.svg,
    # /favicon.ico, and /_next/, etc.
    file_path = os.path.join(server_constants.DASHBOARD_DIR, safe_full_path)
    if os.path.isfile(file_path):
        if file_path.endswith('.html'):
            return _serve_html_with_nonce(request, file_path)
        return fastapi.responses.FileResponse(file_path)

    # Build assets under _next/ are content-hashed static files; a missing
    # one must 404 instead of falling through to the index.html SPA shell
    # below. Returning HTML (200) for a missing .js/.css lets a CDN cache the
    # shell under the asset URL, which then fails the browser's strict MIME
    # check and blanks the dashboard until the cache entry expires.
    if safe_full_path.startswith('_next/'):
        raise fastapi.HTTPException(status_code=404,
                                    detail='Not found',
                                    headers={'Cache-Control': 'no-store'})

    # Try serving a pre-rendered HTML page for the path.
    # e.g. /clusters -> clusters.html, /jobs -> jobs.html
    html_path = os.path.join(server_constants.DASHBOARD_DIR,
                             f'{safe_full_path}.html')
    if os.path.isfile(html_path):
        return _serve_html_with_nonce(request, html_path)

    # Resolve Next.js dynamic routes using the routes manifest.
    # Handles patterns like:
    #   /clusters/my-cluster  -> clusters/[cluster].html
    #   /jobs/123/456         -> jobs/[job]/[task].html
    #   /plugins/foo/bar      -> plugins/[...slug].html
    if safe_full_path:
        resolved = _resolve_dynamic_route(server_constants.DASHBOARD_DIR,
                                          safe_full_path)
        if resolved is not None:
            return _serve_html_with_nonce(request, resolved)

    # Serve index.html as a last resort.
    index_path = os.path.join(server_constants.DASHBOARD_DIR, 'index.html')
    try:
        return _serve_html_with_nonce(request, index_path)
    except Exception as e:
        logger.error(f'Error serving dashboard: {e}')
        raise fastapi.HTTPException(status_code=500, detail=str(e))


# Redirect the root path to dashboard
@router.get('/')
async def root():
    return fastapi.responses.RedirectResponse(url='/dashboard/')
