/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/X5tLGA3WPNU
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import React, { useState, useEffect } from 'react';
import { CircularProgress } from '@mui/material';
import { Layout } from '@/components/elements/layout';
import {
  RotateCwIcon,
  SearchIcon,
  XIcon,
  PlusIcon,
  EditIcon,
} from 'lucide-react';
import { useMobile } from '@/hooks/useMobile';
import { useVisibleRefreshInterval } from '@/hooks/useVisibleRefreshInterval';
import { ContextDetails } from '@/components/infra-context-details';
import {
  InfrastructureSection,
  SkeletonBadge,
} from '@/components/infra-section';
import { canonicalizeGpuName } from '@/utils/gpuUtils';
import {
  getWorkspaceInfrastructure,
  getWorkspaceContexts,
  getContextGPUData,
  getCloudInfrastructure,
  getEnabledCloudsList,
  getContextJobs,
  getContextClusters,
  getSlurmInfrastructure,
} from '@/data/connectors/infra';
import { CLOUDS_LIST } from '@/data/connectors/constants';
import {
  runSkyCheck,
  getWorkspaces,
  getEnabledCloudsBatch,
} from '@/data/connectors/workspaces';
import { getClusters } from '@/data/connectors/clusters';
import { getManagedJobs } from '@/data/connectors/jobs';
import { apiClient } from '@/data/connectors/client';
import {
  getSSHNodePools,
  updateSSHNodePools,
  deleteSSHNodePool,
  deploySSHNodePool,
} from '@/data/connectors/ssh-node-pools';
import { SSHNodePoolModal } from '@/components/ssh-node-pool-modal';
import { SSHNodePoolDetails } from '@/components/ssh-node-pool-details';
import dashboardCache from '@/lib/cache';
import { trackInfraAction } from '@/lib/analytics';
import cachePreloader from '@/lib/cache-preloader';
import { REFRESH_INTERVALS } from '@/lib/config';
import { useRouter } from 'next/router';
import Link from 'next/link';
import { PluginSlot } from '@/plugins/PluginSlot';
import { PluginWrapperSlot } from '@/plugins/PluginWrapperSlot';
import {
  useAllDataProviders,
  usePluginComponents,
} from '@/plugins/PluginProvider';
import {
  NonCapitalizedTooltip,
  LastUpdatedTimestamp,
} from '@/components/utils';
import { Card } from '@/components/ui/card';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';

export { ContextDetails, InfrastructureSection };

// Set the refresh interval to align with other pages
const REFRESH_INTERVAL = REFRESH_INTERVALS.REFRESH_INTERVAL;

export async function loadContextGPUDataInParallel(
  contexts,
  loadContext,
  onSuccess,
  onError
) {
  await Promise.all(
    contexts.map(async (context) => {
      try {
        const gpuData = await loadContext(context);
        onSuccess(context, gpuData);
      } catch (error) {
        onError(context, error);
      }
    })
  );
}

function InfrastructureHint() {
  return (
    <div className="rounded-lg border bg-card text-card-foreground shadow-sm mb-6">
      <div className="p-5">
        <div className="flex items-start">
          <div className="ml-3 flex-1">
            <h3 className="text-lg font-semibold text-gray-900 mb-2">
              No Infrastructure Enabled
            </h3>
            <p className="text-sm text-gray-600 mb-4">
              No cloud providers, Kubernetes contexts, SSH node pools, or Slurm
              clusters are currently enabled or configured.
            </p>
            <div className="space-y-2 mb-4">
              <p className="text-sm text-gray-600">
                To check enabled infrastructures, you can:
              </p>
              <ul className="list-disc list-inside text-sm text-gray-600 space-y-1 ml-2">
                <li>
                  Click <strong>&quot;Refresh&quot;</strong>.
                </li>
                <li>
                  Run{' '}
                  <code className="bg-gray-100 px-1.5 py-0.5 rounded">
                    sky check
                  </code>{' '}
                  in your CLI.
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export function GPUs() {
  // Plugin-contributed extra rows + status data.
  //
  // OSS does not know any plugin id; we discover providers by hook name.
  // Each provider's `useExtraInfraRows` hook is called inside its own
  // child component (`ProviderInfraRowsLoader`, defined below GPUs)
  // rather than directly in GPUs, so adding/removing data providers does
  // NOT change the count of hooks called per GPUs render — that would
  // be a Rules-of-Hooks violation.
  const allDataProviders = useAllDataProviders();
  const extraInfraProviders = React.useMemo(
    () => allDataProviders.filter((p) => p.hooks?.useExtraInfraRows),
    [allDataProviders]
  );
  const [extraInfraResultsById, setExtraInfraResultsById] = useState({});
  const recordExtraInfraResult = React.useCallback((id, result) => {
    setExtraInfraResultsById((prev) => {
      if (prev[id] === result) return prev;
      return { ...prev, [id]: result };
    });
  }, []);
  const hasInfraExtension = extraInfraProviders.length > 0;
  const extraInfraResults = React.useMemo(
    () => Object.values(extraInfraResultsById),
    [extraInfraResultsById]
  );
  const extraInfraRows = React.useMemo(
    () => extraInfraResults.flatMap((r) => r?.rows ?? []),
    [extraInfraResults]
  );
  const extraStatusByKey = React.useMemo(() => {
    const m = new Map();
    for (const r of extraInfraResults) {
      if (!r?.statusByKey) continue;
      for (const [k, v] of r.statusByKey) m.set(k, v);
    }
    return m;
  }, [extraInfraResults]);
  const pluginInfraLoading =
    hasInfraExtension &&
    (extraInfraResults.length < extraInfraProviders.length ||
      extraInfraResults.some((r) => r?.loading));
  const refreshExtraInfra = React.useCallback(
    () =>
      Promise.all(
        extraInfraResults.map((r) => r?.refresh?.(true)).filter(Boolean)
      ),
    [extraInfraResults]
  );

  // Separate loading states for different data sources
  const [kubeLoading, setKubeLoading] = useState(true);
  const [cloudLoading, setCloudLoading] = useState(true);
  const [isInitialLoad, setIsInitialLoad] = useState(true);
  const isMobile = useMobile();
  const [kubeDataLoaded, setKubeDataLoaded] = useState(false);
  const [cloudDataLoaded, setCloudDataLoaded] = useState(false);
  const router = useRouter();

  const [allKubeContextNames, setAllKubeContextNames] = useState([]);
  const [allGPUs, setAllGPUs] = useState([]);
  const [perContextGPUs, setPerContextGPUs] = useState([]);
  const [perNodeGPUs, setPerNodeGPUs] = useState([]);
  // Track which contexts have had their GPU/node data loaded (for progressive loading)
  const [loadedContexts, setLoadedContexts] = useState(new Set());
  const [allSlurmGPUs, setAllSlurmGPUs] = useState([]);
  const [perClusterSlurmGPUs, setPerClusterSlurmGPUs] = useState([]);
  const [perNodeSlurmGPUs, setPerNodeSlurmGPUs] = useState([]);
  const [cloudInfraData, setCloudInfraData] = useState([]);
  const [totalClouds, setTotalClouds] = useState(0);
  // Separate cluster/job counts for Cloud panel (for progressive loading)
  const [cloudClusterCounts, setCloudClusterCounts] = useState({});
  const [cloudJobCounts, setCloudJobCounts] = useState({});
  const [contextStats, setContextStats] = useState({});
  const [contextWorkspaceMap, setContextWorkspaceMap] = useState({});
  const [contextErrors, setContextErrors] = useState({});

  // Workspace-aware infrastructure state
  const [workspaceInfrastructure, setWorkspaceInfrastructure] = useState({});
  const [selectedWorkspace, setSelectedWorkspace] = useState('all');
  const [availableWorkspaces, setAvailableWorkspaces] = useState([]);

  // SSH Node Pool state
  const [sshNodePools, setSshNodePools] = useState({});
  const [sshModalOpen, setSshModalOpen] = useState(false);
  const [editingPool, setEditingPool] = useState(null);
  const [sshLoading, setSshLoading] = useState(false);

  // Slurm loading state (separate from Kubernetes/SSH for parallel loading)
  const [slurmLoading, setSlurmLoading] = useState(true);
  const [slurmDataLoaded, setSlurmDataLoaded] = useState(false);

  const [sshAndKubeJobsDataLoading, setSshAndKubeJobsDataLoading] =
    useState(true);
  const [sshAndKubeJobsData, setSshAndKubeJobsData] = useState({});
  const [clusterDataLoading, setClusterDataLoading] = useState(true);
  const [lastFetchedTime, setLastFetchedTime] = useState(null);

  // Counter incremented on refresh to force GPU metrics iframes to reload.
  // When this value changes, the iframe key changes, causing React to remount the iframe.
  const [gpuMetricsRefreshTrigger, setGpuMetricsRefreshTrigger] = useState(0);

  // Ref to track previous loading state for detecting when loading completes
  const wasLoadingRef = React.useRef(true);

  // Only the newest refresh generation may publish state. Background polls
  // reuse the active refresh instead of starting overlapping duplicate work.
  const refreshStateRef = React.useRef({ generation: 0, active: null });

  // State and refs for tracking the current visible refresh.
  const [isFetching, setIsFetching] = useState(false);

  // Selected context for subpage view
  const [selectedContext, setSelectedContext] = useState(null);

  const fetchData = React.useCallback(
    async (options = { showLoadingIndicators: true }, owner) => {
      const { showLoadingIndicators = true, forceRefresh = false } = options;
      const ownsRefresh = () =>
        refreshStateRef.current.active === owner &&
        refreshStateRef.current.generation === owner.generation;

      if (showLoadingIndicators) {
        setKubeLoading(true);
        setCloudLoading(true);
        setSshLoading(true);
        setSlurmLoading(true);
        setSshAndKubeJobsDataLoading(true);
        setClusterDataLoading(true);
        // Note: Don't reset kubeDataLoaded/cloudDataLoaded here - that would cause
        // the entire panel to show a loading spinner. Instead, keep the table visible
        // and just show inline spinners on the counts via sshAndKubeJobsDataLoading/clusterDataLoading.
      }

      try {
        // Run sky check in parallel with data fetches (not blocking)
        // Sky check refreshes cloud credentials but shouldn't delay data display
        const skyCheckPromise = forceRefresh
          ? runSkyCheck().catch((error) => {
              console.error('Error during sky check refresh:', error);
            })
          : Promise.resolve();

        // Fetch all data in parallel (including sky check)
        // SSH Node Pools are fetched independently - they don't depend on Kubernetes data.
        // The SSH GPU info comes from getWorkspaceInfrastructure() which handles both K8s and SSH contexts.
        await Promise.all([
          skyCheckPromise,
          fetchKubernetesData(forceRefresh, showLoadingIndicators, ownsRefresh),
          fetchSSHNodePools(forceRefresh, ownsRefresh),
          fetchCloudData(forceRefresh, ownsRefresh),
          fetchManagedJobsData(ownsRefresh),
          fetchClusterStatsData(ownsRefresh),
          fetchSlurmData(ownsRefresh),
        ]);
      } catch (error) {
        if (!ownsRefresh()) {
          return;
        }
        console.error('Error in fetchData:', error);
        // On error, we should still mark data as loaded but with empty values
        setWorkspaceInfrastructure({});
        setAllKubeContextNames([]);
        setAllGPUs([]);
        setPerContextGPUs([]);
        setPerNodeGPUs([]);
        setContextStats({});
        setContextWorkspaceMap({});
        setContextErrors({});
        setAvailableWorkspaces([]);
        setKubeDataLoaded(true);
        setKubeLoading(false);
        setClusterDataLoading(false);
        setCloudInfraData([]);
        setTotalClouds(0);
        setCloudClusterCounts({});
        setCloudJobCounts({});
        setCloudDataLoaded(true);
        setSshNodePools({});
        setSshLoading(false);
        setSlurmLoading(false);
        setAllSlurmGPUs([]);
        setPerClusterSlurmGPUs([]);
        setPerNodeSlurmGPUs([]);
        setSshAndKubeJobsData({});
        setSshAndKubeJobsDataLoading(false);
      } finally {
        if (!ownsRefresh()) {
          return;
        }

        // Always clear loading states when showLoadingIndicators is true
        // This prevents infinite loading state
        if (showLoadingIndicators) {
          setKubeLoading(false);
          setCloudLoading(false);
          setSshLoading(false);
          setSlurmLoading(false);
          setSshAndKubeJobsDataLoading(false);
          setClusterDataLoading(false);
        }

        // Set isInitialLoad to false only after the first fetch cycle initiated with showLoadingIndicators:true
        if (isInitialLoad && showLoadingIndicators) {
          setIsInitialLoad(false);
        }
      }
    },
    [isInitialLoad]
  );

  const fetchKubernetesData = async (
    forceRefresh,
    showLoadingIndicators = true,
    ownsRefresh = () => true
  ) => {
    try {
      // Phase 1: Get context names quickly (without GPU data)
      // This allows UI to show contexts immediately while GPU data loads
      const contextsData = forceRefresh
        ? await getWorkspaceContexts()
        : await dashboardCache.get(getWorkspaceContexts);
      if (!ownsRefresh()) {
        return;
      }

      if (!contextsData) {
        setWorkspaceInfrastructure({});
        setAllKubeContextNames([]);
        setAllGPUs([]);
        setPerContextGPUs([]);
        setPerNodeGPUs([]);
        setContextWorkspaceMap({});
        setContextErrors({});
        setAvailableWorkspaces([]);
        setKubeDataLoaded(true);
        setKubeLoading(false);
        return;
      }

      const {
        workspaces: fetchedWorkspaceInfrastructure,
        allContextNames: fetchedAllKubeContextNames,
        contextWorkspaceMap: fetchedContextWorkspaceMap,
      } = contextsData;

      // Update UI immediately with context names (before GPU data loads)
      setWorkspaceInfrastructure(fetchedWorkspaceInfrastructure || {});
      setAllKubeContextNames(fetchedAllKubeContextNames || []);
      setContextWorkspaceMap(fetchedContextWorkspaceMap || {});

      // Extract available workspaces
      const workspaceNames = Object.keys(fetchedWorkspaceInfrastructure || {});
      setAvailableWorkspaces(workspaceNames.sort());

      // Mark contexts as loaded so UI can show them (GPU details will fill in progressively)
      setKubeDataLoaded(true);
      setKubeLoading(false);

      // Phase 2: Fetch GPU data for each context in parallel, updating UI as each completes
      const validContexts = (fetchedAllKubeContextNames || []).filter(
        (context) => context && typeof context === 'string'
      );

      if (validContexts.length === 0) {
        // No contexts to fetch GPU data for
        // Only clear data during initial/manual refresh, not interval refresh
        if (showLoadingIndicators) {
          setAllGPUs([]);
          setPerContextGPUs([]);
          setPerNodeGPUs([]);
          setContextErrors({});
          setLoadedContexts(new Set());
        }
        return;
      }

      // Reset loadedContexts to show spinners in info columns during refresh
      // But DON'T clear GPU data arrays - this keeps the GPU panel visible with existing data
      // while new data loads progressively
      if (showLoadingIndicators) {
        setLoadedContexts(new Set()); // Reset to show spinners
        setContextErrors({}); // Clear errors for fresh fetch
      }

      // Fetch GPU data for all contexts in parallel, updating state as each completes
      // For manual refresh (forceRefresh), fetch fresh data directly
      // For interval refresh (!forceRefresh), use cache for quick response
      await loadContextGPUDataInParallel(
        validContexts,
        (context) =>
          forceRefresh
            ? getContextGPUData(context)
            : dashboardCache.get(getContextGPUData, [context]),
        (context, gpuData) => {
          if (!ownsRefresh()) {
            return;
          }
          // Mark this context as loaded (even if it has no GPUs)
          setLoadedContexts((prev) => new Set([...prev, context]));

          // Update perContextGPUs - merge in data for this context
          setPerContextGPUs((prev) => {
            // Remove any existing entries for this context, then add new ones
            const filtered = prev.filter((gpu) => gpu.context !== context);
            return [...filtered, ...gpuData.perContextGPUs];
          });

          // Update perNodeGPUs - merge in data for this context
          setPerNodeGPUs((prev) => {
            const filtered = prev.filter((node) => node.context !== context);
            return [...filtered, ...gpuData.perNodeGPUs];
          });

          // Note: allGPUs is computed via useEffect when perContextGPUs changes

          // Update context errors if there was an error
          if (gpuData.error) {
            setContextErrors((prev) => ({
              ...prev,
              [context]: gpuData.error,
            }));
          }
        },
        (context, error) => {
          if (!ownsRefresh()) {
            return;
          }
          // Mark context as loaded even on error to prevent infinite spinner
          setLoadedContexts((prev) => new Set([...prev, context]));
          setContextErrors((prev) => ({
            ...prev,
            [context]: error.message || 'Failed to load GPU data',
          }));
        }
      );
    } catch (error) {
      if (!ownsRefresh()) {
        return;
      }
      console.error('Error in fetchKubernetesData:', error);
      setWorkspaceInfrastructure({});
      setAllKubeContextNames([]);
      setAllGPUs([]);
      setPerContextGPUs([]);
      setPerNodeGPUs([]);
      setContextWorkspaceMap({});
      setContextErrors({});
      setAvailableWorkspaces([]);
      setKubeDataLoaded(true);
      setKubeLoading(false);
    }
  };

  const fetchManagedJobsData = async (ownsRefresh = () => true) => {
    try {
      // Always use cache - it's already invalidated if refreshing
      // Jobs data doesn't depend on sky check, so no need to bypass cache
      // Use shared cache key (no field filtering) - preloader uses same args
      const jobsData = await dashboardCache.get(getManagedJobs, [
        { allUsers: true, skipFinished: true },
      ]);
      if (!ownsRefresh()) {
        return;
      }
      const jobs = jobsData?.jobs || [];
      setSshAndKubeJobsData(await getContextJobs(jobs));
      if (!ownsRefresh()) {
        return;
      }

      // Also compute cloud job counts for the Cloud panel (progressive loading)
      const cloudCounts = {};
      jobs.forEach((job) => {
        if (job.cloud) {
          cloudCounts[job.cloud] = (cloudCounts[job.cloud] || 0) + 1;
        }
      });
      setCloudJobCounts(cloudCounts);

      setSshAndKubeJobsDataLoading(false);
    } catch (error) {
      if (!ownsRefresh()) {
        return;
      }
      console.error('Error in fetchManagedJobsData:', error);
      setSshAndKubeJobsData({});
      setCloudJobCounts({});
      setSshAndKubeJobsDataLoading(false);
    }
  };

  // Fetch cluster stats separately for fast loading (similar to jobs)
  const fetchClusterStatsData = async (ownsRefresh = () => true) => {
    try {
      // Get clusters from cache (fast - already cached)
      const clustersData = await dashboardCache.get(getClusters);
      if (!ownsRefresh()) {
        return;
      }
      const clusters = clustersData || [];
      // Compute cluster stats per context (fast - local computation)
      const clusterStats = await getContextClusters(clusters);
      if (!ownsRefresh()) {
        return;
      }
      setContextStats(clusterStats);

      // Also compute cloud cluster counts for the Cloud panel (progressive loading)
      const cloudCounts = {};
      clusters.forEach((cluster) => {
        if (cluster.cloud) {
          cloudCounts[cluster.cloud] = (cloudCounts[cluster.cloud] || 0) + 1;
        }
      });
      setCloudClusterCounts(cloudCounts);

      setClusterDataLoading(false);
    } catch (error) {
      if (!ownsRefresh()) {
        return;
      }
      console.error('Error in fetchClusterStatsData:', error);
      setContextStats({});
      setCloudClusterCounts({});
      setClusterDataLoading(false);
    }
  };

  // Fetch Slurm data separately for parallel loading with Kubernetes/SSH
  const fetchSlurmData = async (ownsRefresh = () => true) => {
    try {
      const slurmData = await dashboardCache.get(getSlurmInfrastructure);
      if (!ownsRefresh()) {
        return;
      }
      if (slurmData) {
        setAllSlurmGPUs(slurmData.allSlurmGPUs || []);
        setPerClusterSlurmGPUs(slurmData.perClusterSlurmGPUs || []);
        setPerNodeSlurmGPUs(slurmData.perNodeSlurmGPUs || []);
      }
      setSlurmDataLoaded(true);
      setSlurmLoading(false);
    } catch (error) {
      if (!ownsRefresh()) {
        return;
      }
      console.error('Error in fetchSlurmData:', error);
      setAllSlurmGPUs([]);
      setPerClusterSlurmGPUs([]);
      setPerNodeSlurmGPUs([]);
      setSlurmDataLoaded(true);
      setSlurmLoading(false);
    }
  };

  // Fetch enabled clouds list fast (without counts) for progressive loading
  // Counts come from cloudClusterCounts and cloudJobCounts (computed separately)
  const fetchCloudData = async (forceRefresh, ownsRefresh = () => true) => {
    try {
      // Use fast function that only gets enabled cloud names (no counts)
      const cloudData = forceRefresh
        ? await getEnabledCloudsList()
        : await dashboardCache.get(getEnabledCloudsList);
      if (!ownsRefresh()) {
        return;
      }

      // Set cloud data with defensive checks
      if (cloudData) {
        setCloudInfraData(cloudData.clouds || []);
        setTotalClouds(cloudData.totalClouds || 0);
        setCloudDataLoaded(true);
      } else if (cloudData === null) {
        // Data was explicitly null (not just missing)
        setCloudInfraData([]);
        setTotalClouds(0);
        setCloudDataLoaded(true);
      }
      // Clear loading state as soon as Cloud list is ready
      setCloudLoading(false);
    } catch (error) {
      if (!ownsRefresh()) {
        return;
      }
      console.error('Error in fetchCloudData:', error);
      setCloudInfraData([]);
      setTotalClouds(0);
      setCloudDataLoaded(true);
      setCloudLoading(false);
    }
  };

  // SSH Node Pool data fetching
  const fetchSSHNodePools = async (forceRefresh, ownsRefresh = () => true) => {
    try {
      const pools = forceRefresh
        ? await getSSHNodePools()
        : await dashboardCache.get(getSSHNodePools);
      if (!ownsRefresh()) {
        return;
      }
      setSshNodePools(pools);
      setSshLoading(false);
    } catch (error) {
      if (!ownsRefresh()) {
        return;
      }
      console.error('Failed to fetch SSH Node Pools:', error);
      setSshNodePools({});
      setSshLoading(false);
    }
  };

  const startRefresh = React.useCallback(
    (options = { showLoadingIndicators: true }) => {
      const { showLoadingIndicators = true } = options;
      const state = refreshStateRef.current;
      if (state.active !== null && !showLoadingIndicators) {
        return state.active.promise;
      }

      const owner = {
        generation: ++state.generation,
        promise: null,
      };
      state.active = owner;
      setIsFetching(true);
      owner.promise = fetchData(options, owner).finally(() => {
        if (state.active === owner && state.generation === owner.generation) {
          state.active = null;
          setIsFetching(false);
        }
      });
      return owner.promise;
    },
    [fetchData]
  );

  // SSH Node Pool handlers
  const handleAddSSHPool = () => {
    setEditingPool(null);
    setSshModalOpen(true);
  };

  const handleEditSSHPool = (poolName, poolConfig) => {
    setEditingPool({ name: poolName, config: poolConfig });
    setSshModalOpen(true);
  };

  const handleDeleteSSHPool = async (poolName) => {
    try {
      // Just handle the actual deletion and navigation
      // The streaming is now handled in the SSHNodePoolDetails component
      await deleteSSHNodePool(poolName);
      await fetchSSHNodePools(); // Refresh the list

      // Clear selected context and navigate back to infra home page after successful deletion
      setSelectedContext(null);
      router.push('/infra');
    } catch (error) {
      console.error('Failed to delete SSH Node Pool:', error);
      // Let the error bubble up to be handled by the dialog
      throw error;
    }
  };

  const handleDeploySSHPool = async (poolName) => {
    try {
      return await deploySSHNodePool(poolName);
    } catch (error) {
      console.error('Failed to deploy SSH Node Pool:', error);
      // Let the error bubble up to be handled by the dialog
      throw error;
    }
  };

  const handleSaveSSHPool = async (poolName, poolConfig) => {
    setSshLoading(true);
    try {
      const updatedPools = { ...sshNodePools };
      updatedPools[poolName] = poolConfig;

      await updateSSHNodePools(updatedPools);
      await fetchSSHNodePools(); // Refresh the list
      setSshModalOpen(false);
    } catch (error) {
      console.error('Failed to save SSH Node Pool:', error);
      alert('Failed to save SSH Node Pool. Please try again.');
    } finally {
      setSshLoading(false);
    }
  };

  // Compute allGPUs (aggregated totals) whenever perContextGPUs changes
  useEffect(() => {
    const gpuSummary = {};
    perContextGPUs.forEach((gpu) => {
      const gpuName = canonicalizeGpuName(gpu.gpu_name);
      if (gpuName in gpuSummary) {
        gpuSummary[gpuName].gpu_total += gpu.gpu_total || 0;
        gpuSummary[gpuName].gpu_free += gpu.gpu_free || 0;
        gpuSummary[gpuName].gpu_not_ready += gpu.gpu_not_ready || 0;
      } else {
        gpuSummary[gpuName] = {
          gpu_name: gpuName,
          gpu_total: gpu.gpu_total || 0,
          gpu_free: gpu.gpu_free || 0,
          gpu_not_ready: gpu.gpu_not_ready || 0,
        };
      }
    });
    setAllGPUs(Object.values(gpuSummary));
  }, [perContextGPUs]);

  // Effect for initial load.
  useEffect(() => {
    // This calls the fetchData version defined when isInitialLoad is true.
    // That fetchData will then set isInitialLoad to false within its finally block.
    const initializeData = async () => {
      // Trigger cache preloading for infra page and background preload other pages
      await cachePreloader.preloadForPage('infra');

      await startRefresh({ showLoadingIndicators: true });
    };

    initializeData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useVisibleRefreshInterval(
    !isInitialLoad,
    REFRESH_INTERVAL,
    () => {
      startRefresh({ showLoadingIndicators: false });
    },
    {
      catchUpOnlyWhenOverdue: true,
    }
  );

  // Reset states when component unmounts
  useEffect(() => {
    const refreshState = refreshStateRef.current;
    return () => {
      // Don't invalidate cache on unmount - this was causing premature cache invalidation
      // Cache should only be invalidated on manual refresh or TTL expiration
      // Reset loading states for fresh load next time
      setKubeDataLoaded(false);
      setCloudDataLoaded(false);
      setSshLoading(false);
      setSlurmLoading(false);
      setSlurmDataLoaded(false);
      setIsInitialLoad(true);
      setSshAndKubeJobsDataLoading(false);
      setClusterDataLoading(false);
      refreshState.generation += 1;
      refreshState.active = null;
      setIsFetching(false);
    };
  }, []);

  // Memoized so the keyboard-shortcut and `skydashboard:infra:refresh`
  // listeners below close over a fresh refreshExtraInfra each render.
  // Without this, the listeners capture the first-render handleRefresh
  // (which closes over an empty extraInfraResults) and never see the
  // plugin-contributed results that resolve after first paint.
  const handleRefresh = React.useCallback(async () => {
    trackInfraAction('refresh');
    // Invalidate cache to ensure fresh data is fetched
    dashboardCache.invalidate(getClusters);
    dashboardCache.invalidate(getManagedJobs, [
      { allUsers: true, skipFinished: true },
    ]);
    dashboardCache.invalidate(getWorkspaceContexts);
    dashboardCache.invalidate(getWorkspaceInfrastructure); // Keep for backwards compatibility
    dashboardCache.invalidate(getEnabledCloudsList);
    // `getWorkspaceContexts` reads `getEnabledCloudsBatch` internally
    // through the cache; without this invalidation, re-running
    // `getWorkspaceContexts` after Refresh sees a stale batch and
    // reports outdated context lists. invalidateFunction clears every
    // (workspaces, expand) variant in one call.
    dashboardCache.invalidateFunction(getEnabledCloudsBatch);
    dashboardCache.invalidate(getCloudInfrastructure, [false]); // Keep for backwards compatibility
    dashboardCache.invalidate(getSSHNodePools);
    dashboardCache.invalidate(getSlurmInfrastructure);

    // Increment GPU metrics refresh trigger to force iframe reload
    setGpuMetricsRefreshTrigger((prev) => prev + 1);

    // Run OSS data refresh and plugin extras refresh in parallel so the
    // status dots update as soon as the (much faster) plugin call returns
    // — without this, dots stay frozen on stale data until the slower
    // sky-check pass finishes.
    await Promise.all([
      startRefresh({
        showLoadingIndicators: true,
        forceRefresh: true, // Force refresh to run sky check
      }),
      refreshExtraInfra(),
    ]);
  }, [refreshExtraInfra, startRefresh]);

  // Effect for keyboard shortcut (Cmd+R / Ctrl+R) to force refresh
  useEffect(() => {
    const handleKeyDown = (event) => {
      // Check for Cmd+R (Mac) or Ctrl+R (Windows/Linux)
      if ((event.metaKey || event.ctrlKey) && event.key === 'r') {
        event.preventDefault(); // Prevent browser refresh
        handleRefresh(); // Trigger our force refresh
      }
    };

    window.addEventListener('keydown', handleKeyDown);

    return () => {
      window.removeEventListener('keydown', handleKeyDown);
    };
  }, [handleRefresh]);

  // Listen for plugin-emitted refresh requests, e.g. when a plugin's
  // "Add infra" / "Remove infra" flow finishes, so the host page picks up
  // the new state without the user having to click Refresh manually.
  useEffect(() => {
    const onRefreshEvent = () => handleRefresh();
    window.addEventListener('skydashboard:infra:refresh', onRefreshEvent);
    return () => {
      window.removeEventListener('skydashboard:infra:refresh', onRefreshEvent);
    };
  }, [handleRefresh]);

  // Calculate summary data
  const totalGpuTypes = (allGPUs || []).length;
  const grandTotalGPUs = (allGPUs || []).reduce(
    (sum, gpu) => sum + gpu.gpu_total,
    0
  );
  const grandTotalFreeGPUs = (allGPUs || []).reduce(
    (sum, gpu) => sum + gpu.gpu_free,
    0
  );

  // Group perContextGPUs by context (already flattened from the backend)
  const groupedPerContextGPUs = React.useMemo(() => {
    if (!perContextGPUs) return {};
    return perContextGPUs.reduce((acc, gpu) => {
      const { context } = gpu;
      if (!acc[context]) {
        acc[context] = [];
      }
      acc[context].push(gpu);
      return acc;
    }, {});
  }, [perContextGPUs]);

  // Filter contexts based on selected workspace
  const filterContextsByWorkspace = React.useCallback(
    (contexts) => {
      if (selectedWorkspace === 'all') {
        return contexts;
      }
      return contexts.filter((context) => {
        const workspaces = contextWorkspaceMap[context] || [];
        return workspaces.includes(selectedWorkspace);
      });
    },
    [selectedWorkspace, contextWorkspaceMap]
  );

  // Get enabled clouds for the selected workspace
  const workspaceEnabledClouds = React.useMemo(() => {
    // If Kubernetes data is still loading and workspaceInfrastructure is empty,
    // return null to indicate we should show all enabled clouds without filtering
    if (kubeLoading && Object.keys(workspaceInfrastructure).length === 0) {
      return null;
    }

    if (selectedWorkspace === 'all') {
      // Return all unique clouds across all workspaces
      const allCloudsSet = new Set();
      Object.values(workspaceInfrastructure).forEach((wsData) => {
        if (wsData.clouds && Array.isArray(wsData.clouds)) {
          wsData.clouds.forEach((cloud) => {
            // Extract base cloud name (e.g., 'aws' from 'aws', 'kubernetes' from 'kubernetes/context')
            const baseCloud = cloud.toLowerCase().split('/')[0];
            allCloudsSet.add(baseCloud);
          });
        }
      });
      return Array.from(allCloudsSet);
    } else {
      // Return clouds for the selected workspace only
      const wsData = workspaceInfrastructure[selectedWorkspace];
      if (!wsData || !wsData.clouds || !Array.isArray(wsData.clouds)) {
        return [];
      }
      const cloudsSet = new Set();
      wsData.clouds.forEach((cloud) => {
        const baseCloud = cloud.toLowerCase().split('/')[0];
        cloudsSet.add(baseCloud);
      });
      return Array.from(cloudsSet);
    }
  }, [selectedWorkspace, workspaceInfrastructure, kubeLoading]);

  // Filter cloud infrastructure data based on selected workspace, then merge
  // in any plugin-contributed cloud rows (e.g. misconfigured clouds that have
  // credentials registered but didn't show up in workspace-enabled clouds).
  const filteredCloudInfraData = React.useMemo(() => {
    const base = (() => {
      if (!cloudInfraData || cloudInfraData.length === 0) return [];
      if (workspaceEnabledClouds === null) return cloudInfraData;
      return cloudInfraData.filter((cloud) =>
        workspaceEnabledClouds.includes(cloud.name.toLowerCase())
      );
    })();
    // Merge plugin-contributed cloud rows by id (case-insensitive).
    const seen = new Set(base.map((c) => (c.id || c.name || '').toLowerCase()));
    const extras = extraInfraRows
      .filter((r) => r.kind === 'cloud')
      .filter((r) => !seen.has((r.id || '').toLowerCase()))
      .map((r) => ({
        id: r.id,
        name: r.name || r.id,
        clusters: 0,
        jobs: 0,
        // Storage-only infrastructure (object storage that cannot host
        // clusters or managed jobs). Such rows render a "—" in the Clusters
        // and Jobs columns instead of a misleading 0.
        storageOnly: r.storageOnly === true,
      }));
    return [...base, ...extras];
  }, [cloudInfraData, workspaceEnabledClouds, extraInfraRows]);

  // Calculate enabled clouds count for the selected workspace
  const filteredEnabledCloudsCount = React.useMemo(() => {
    return filteredCloudInfraData.length;
  }, [filteredCloudInfraData]);

  // Separate SSH contexts from Kubernetes contexts using allKubeContextNames
  const sshContexts = React.useMemo(() => {
    if (!allKubeContextNames || !Array.isArray(allKubeContextNames)) {
      return [];
    }
    const contexts = allKubeContextNames.filter((context) =>
      context.startsWith('ssh-')
    );
    return filterContextsByWorkspace(contexts);
  }, [allKubeContextNames, filterContextsByWorkspace]);

  const kubeContexts = React.useMemo(() => {
    if (!allKubeContextNames || !Array.isArray(allKubeContextNames)) {
      return [];
    }
    const contexts = allKubeContextNames.filter(
      (context) => !context.startsWith('ssh-')
    );
    return filterContextsByWorkspace(contexts);
  }, [allKubeContextNames, filterContextsByWorkspace]);

  // Filter GPUs by context type (SSH vs Kubernetes)
  const sshGPUs = React.useMemo(() => {
    if (!perContextGPUs || !allGPUs) return [];

    // Create a map of GPU names from SSH contexts
    const sshGpuNames = new Set();
    perContextGPUs.forEach((gpu) => {
      if (gpu.context.startsWith('ssh-')) {
        sshGpuNames.add(canonicalizeGpuName(gpu.gpu_name));
      }
    });

    // Filter allGPUs based on whether they appear in SSH contexts
    return allGPUs.filter((gpu) => sshGpuNames.has(gpu.gpu_name));
  }, [allGPUs, perContextGPUs]);

  const kubeGPUs = React.useMemo(() => {
    if (!perContextGPUs || !allGPUs) return [];

    // Create a map of GPU names from Kubernetes contexts
    const kubeGpuNames = new Set();
    perContextGPUs.forEach((gpu) => {
      if (!gpu.context.startsWith('ssh-')) {
        kubeGpuNames.add(canonicalizeGpuName(gpu.gpu_name));
      }
    });

    // Filter allGPUs based on whether they appear in Kubernetes contexts
    return allGPUs.filter((gpu) => kubeGpuNames.has(gpu.gpu_name));
  }, [allGPUs, perContextGPUs]);

  // Extract Slurm cluster names from perClusterSlurmGPUs
  const slurmClusters = React.useMemo(() => {
    if (!perClusterSlurmGPUs || !Array.isArray(perClusterSlurmGPUs)) {
      return [];
    }
    const clusters = [
      ...new Set(perClusterSlurmGPUs.map((gpu) => gpu.cluster)),
    ];
    return clusters.sort();
  }, [perClusterSlurmGPUs]);

  // Group perClusterSlurmGPUs by cluster
  const groupedPerClusterSlurmGPUs = React.useMemo(() => {
    if (!perClusterSlurmGPUs) return {};
    return perClusterSlurmGPUs.reduce((acc, gpu) => {
      const { cluster } = gpu;
      if (!acc[cluster]) {
        acc[cluster] = [];
      }
      acc[cluster].push(gpu);
      return acc;
    }, {});
  }, [perClusterSlurmGPUs]);

  // Group perNodeSlurmGPUs by cluster
  const groupedPerNodeSlurmGPUs = React.useMemo(() => {
    if (!perNodeSlurmGPUs) return {};
    return perNodeSlurmGPUs.reduce((acc, node) => {
      const { cluster } = node;
      if (!acc[cluster]) {
        acc[cluster] = [];
      }
      acc[cluster].push(node);
      return acc;
    }, {});
  }, [perNodeSlurmGPUs]);

  // Group perNodeGPUs by context
  const groupedPerNodeGPUs = React.useMemo(() => {
    if (!perNodeGPUs) return {};
    return perNodeGPUs.reduce((acc, node) => {
      const { context } = node;
      if (!acc[context]) {
        acc[context] = [];
      }
      acc[context].push(node);
      return acc;
    }, {});
  }, [perNodeGPUs]);

  // Check if all infrastructure is disabled
  const allInfrastructureDisabled = (() => {
    // Ensure all data has been loaded
    if (
      !cloudDataLoaded ||
      !kubeDataLoaded ||
      !slurmDataLoaded ||
      kubeLoading ||
      cloudLoading ||
      slurmLoading ||
      pluginInfraLoading
    ) {
      return false; // Still loading, don't show hint
    }

    // Check all infrastructure types
    const noCloud = filteredEnabledCloudsCount === 0;
    const noSSH = sshContexts.length === 0;
    const noKubernetes = kubeContexts.length === 0;
    const noSlurm = slurmClusters.length === 0;

    return noCloud && noSSH && noKubernetes && noSlurm;
  })();

  // Check URL on component mount to set initial context
  useEffect(() => {
    if (router.isReady && router.query.context) {
      // The dynamic route is a catch-all (`[...context].js`), so the
      // segments come back as an array — rejoin them so context names
      // containing slashes (e.g. EKS ARNs) survive a page refresh.
      const contextParam = Array.isArray(router.query.context)
        ? router.query.context.join('/')
        : router.query.context;
      setSelectedContext(decodeURIComponent(contextParam));
    }
  }, [router.isReady, router.query.context]);

  // Handler for clicking on a context
  const handleContextClick = (context) => {
    trackInfraAction('view_context');
    // Don't setSelectedContext here — let the URL effect on the
    // destination page set it. Setting it locally causes the source
    // /infra page to render the context-detail view briefly (firing
    // its data fetches and mounting any plugin slots) right before
    // router.push unmounts it, which doubles every fetch on
    // navigation and delays the user-visible status by the time the
    // destination's mount fights for connection slots against OSS's
    // own enabled_clouds calls.
    const targetPath = `/infra/${encodeURIComponent(context)}`;
    if (router.asPath !== targetPath) {
      router.push(targetPath);
    }
  };

  // Handler to go back to main view
  const handleBackClick = () => {
    setSelectedContext(null);
    // Use push instead of replace for proper browser history
    // Only navigate if we're not already on the infra page
    if (router.asPath !== '/infra') {
      router.push('/infra');
    }
  };

  // Render context details
  const renderContextDetails = (contextName) => {
    // Check if this is a Slurm cluster
    const isSlurmCluster = slurmClusters.includes(contextName);

    // Get the appropriate GPU and node data based on context type
    const gpusInContext = isSlurmCluster
      ? groupedPerClusterSlurmGPUs[contextName] || []
      : groupedPerContextGPUs[contextName] || [];
    const nodesInContext = isSlurmCluster
      ? groupedPerNodeSlurmGPUs[contextName] || []
      : groupedPerNodeGPUs[contextName] || [];

    // Check if this is an SSH context
    const isSSHContext = contextName.startsWith('ssh-');

    if (isSSHContext) {
      // Extract pool name from context (remove 'ssh-' prefix)
      const poolName = contextName.replace(/^ssh-/, '');
      return (
        <SSHNodePoolDetails
          poolName={poolName}
          gpusInContext={gpusInContext}
          nodesInContext={nodesInContext}
          handleDeploySSHPool={handleDeploySSHPool}
          handleEditSSHPool={handleEditSSHPool}
          handleDeleteSSHPool={handleDeleteSSHPool}
          poolConfig={sshNodePools[poolName]}
        />
      );
    }

    // For Kubernetes and Slurm contexts, show the regular context details
    return (
      <ContextDetails
        contextName={contextName}
        gpusInContext={gpusInContext}
        nodesInContext={nodesInContext}
        gpuMetricsRefreshTrigger={gpuMetricsRefreshTrigger}
        isSlurm={isSlurmCluster}
      />
    );
  };

  // Cloud rows are only styled as clickable links when a plugin is wrapping
  // them with the infra.cloudRow.link slot — pure OSS has no per-cloud
  // detail page, so making them look clickable would be misleading.
  const cloudRowIsClickable =
    usePluginComponents('infra.cloudRow.link').length > 0;

  const renderCloudInfrastructure = () => {
    // Show panel-level loading spinner only during initial load when no cloud data at all
    // On subsequent loads, show the table structure with cell-level spinners instead
    if (
      isInitialLoad &&
      cloudLoading &&
      (!cloudInfraData || cloudInfraData.length === 0)
    ) {
      return (
        <div className="rounded-lg border bg-card text-card-foreground shadow-sm mb-6">
          <div className="p-5">
            <h3 className="text-lg font-semibold mb-4">Cloud</h3>
            <div className="flex items-center justify-center py-6">
              <CircularProgress size={24} className="mr-3" />
              <span className="text-gray-500">Loading Cloud...</span>
            </div>
          </div>
        </div>
      );
    }

    return (
      <div className="rounded-lg border bg-card text-card-foreground shadow-sm mb-6">
        <div className="p-5">
          <div className="flex items-center mb-4">
            <h3 className="text-lg font-semibold">Cloud</h3>
            <span className="ml-2 px-2 py-0.5 bg-blue-100 text-blue-800 rounded-full text-xs font-medium">
              {filteredEnabledCloudsCount} of {totalClouds} enabled
            </span>
          </div>
          {!filteredCloudInfraData || filteredCloudInfraData.length === 0 ? (
            (cloudLoading && !cloudDataLoaded) ||
            (hasInfraExtension && pluginInfraLoading) ? (
              // Don't show "No enabled clouds" while we're still waiting on
              // either OSS's cloud fetch or a plugin-contributed data feed —
              // either could still surface clouds before the table renders.
              <div className="flex items-center py-2 text-sm text-gray-500">
                <CircularProgress size={16} className="mr-2" />
                Loading...
              </div>
            ) : (
              <p className="text-sm text-gray-500">
                {selectedWorkspace === 'all'
                  ? 'No enabled clouds available.'
                  : `No enabled clouds for workspace "${selectedWorkspace}".`}
              </p>
            )
          ) : (
            <div
              className={`overflow-x-auto rounded-md border shadow-sm bg-card ${
                !isInitialLoad &&
                (clusterDataLoading || sshAndKubeJobsDataLoading)
                  ? 'infra-table-refreshing'
                  : ''
              }`}
            >
              <table className="min-w-full text-sm">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="p-3 text-left font-medium text-gray-600 w-32">
                      Cloud
                    </th>
                    <th className="p-3 text-left font-medium text-gray-600 w-24">
                      Clusters
                    </th>
                    <th className="p-3 text-left font-medium text-gray-600 w-24">
                      Jobs
                    </th>
                    <th className="p-3 text-right font-medium text-gray-600 w-12" />
                  </tr>
                </thead>
                <tbody className="bg-card divide-y divide-gray-200">
                  {filteredCloudInfraData.map((cloud) => {
                    // Use separate loading states for progressive loading
                    // Clusters and jobs load independently (clusters often ready first)
                    const clusterCount =
                      cloudClusterCounts[cloud.name] ?? cloud.clusters;
                    const jobCount = cloudJobCounts[cloud.name] ?? cloud.jobs;
                    const cloudId = (
                      cloud.id ||
                      cloud.name ||
                      ''
                    ).toLowerCase();

                    const rowInner = (
                      <>
                        <td className="p-3">
                          <div className="flex items-center gap-1.5">
                            <PluginSlot
                              name="infra.row.namePrefix"
                              context={{
                                id: cloudId,
                                kind: 'cloud',
                                status: extraStatusByKey?.get(
                                  `cloud:${cloudId}`
                                ),
                              }}
                            />
                            <span
                              className={
                                cloudRowIsClickable
                                  ? 'text-blue-600 hover:underline cursor-pointer font-medium'
                                  : 'font-medium text-gray-700'
                              }
                            >
                              {cloud.name}
                            </span>
                          </div>
                        </td>
                        <td className="p-3">
                          {cloud.storageOnly ? (
                            <NonCapitalizedTooltip content="Storage-only infrastructure does not run clusters">
                              <span className="px-1.5 py-0.5 text-gray-400 text-xs font-medium cursor-help">
                                —
                              </span>
                            </NonCapitalizedTooltip>
                          ) : clusterDataLoading ? (
                            <SkeletonBadge />
                          ) : (
                            <span className="px-2 py-0.5 bg-gray-100 text-gray-500 rounded text-xs font-medium">
                              {clusterCount ?? 0}
                            </span>
                          )}
                        </td>
                        <td className="p-3">
                          {cloud.storageOnly ? (
                            <NonCapitalizedTooltip content="Storage-only infrastructure does not run managed jobs">
                              <span className="px-1.5 py-0.5 text-gray-400 text-xs font-medium cursor-help">
                                —
                              </span>
                            </NonCapitalizedTooltip>
                          ) : sshAndKubeJobsDataLoading ? (
                            <SkeletonBadge />
                          ) : (
                            <span className="px-2 py-0.5 bg-gray-100 text-gray-500 rounded text-xs font-medium">
                              {jobCount ?? 0}
                            </span>
                          )}
                        </td>
                        <td className="p-3 text-right">
                          <PluginSlot
                            name="infra.row.actions"
                            context={{ id: cloudId, kind: 'cloud' }}
                          />
                        </td>
                      </>
                    );

                    // PluginWrapperSlot renders `children` when no plugin is
                    // registered, so we don't need an explicit fallback.
                    return (
                      <PluginWrapperSlot
                        key={cloud.name}
                        name="infra.cloudRow.link"
                        context={{ id: cloudId }}
                      >
                        <tr className="hover:bg-muted/50">{rowInner}</tr>
                      </PluginWrapperSlot>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>
    );
  };

  const renderSSHNodePoolInfrastructure = () => {
    return (
      <InfrastructureSection
        title="SSH Node Pool"
        isLoading={kubeLoading}
        isDataLoaded={kubeDataLoaded}
        contexts={sshContexts}
        gpus={sshGPUs}
        groupedPerContextGPUs={groupedPerContextGPUs}
        groupedPerNodeGPUs={groupedPerNodeGPUs}
        handleContextClick={handleContextClick}
        contextStats={contextStats}
        jobsData={sshAndKubeJobsData}
        isJobsDataLoading={sshAndKubeJobsDataLoading}
        isClusterDataLoading={clusterDataLoading}
        isSSH={true}
        contextWorkspaceMap={contextWorkspaceMap}
        contextErrors={contextErrors}
        gpuMetricsRefreshTrigger={gpuMetricsRefreshTrigger}
        loadedContexts={loadedContexts}
        isInitialLoad={isInitialLoad}
        statusByKey={extraStatusByKey}
        actionButton={
          // TODO: Add back when SSH Node Pool add operation is more robust
          // <button
          //   className="px-3 py-1 text-sm border border-gray-300 rounded hover:bg-gray-50 flex items-center"
          //   onClick={handleAddSSHPool}
          // >
          //   <PlusIcon className="w-4 h-4 mr-2" />
          //   Add SSH Node Pool
          // </button>
          null
        }
      />
    );
  };

  const renderKubernetesInfrastructure = () => {
    return (
      <InfrastructureSection
        title="Kubernetes"
        isLoading={kubeLoading}
        isDataLoaded={kubeDataLoaded}
        contexts={kubeContexts}
        gpus={kubeGPUs}
        groupedPerContextGPUs={groupedPerContextGPUs}
        groupedPerNodeGPUs={groupedPerNodeGPUs}
        handleContextClick={handleContextClick}
        contextStats={contextStats}
        jobsData={sshAndKubeJobsData}
        isJobsDataLoading={sshAndKubeJobsDataLoading}
        isClusterDataLoading={clusterDataLoading}
        isSSH={false}
        contextWorkspaceMap={contextWorkspaceMap}
        contextErrors={contextErrors}
        gpuMetricsRefreshTrigger={gpuMetricsRefreshTrigger}
        loadedContexts={loadedContexts}
        isInitialLoad={isInitialLoad}
        statusByKey={extraStatusByKey}
      />
    );
  };

  const renderSlurmInfrastructure = () => {
    return (
      <InfrastructureSection
        title="Slurm"
        isLoading={slurmLoading}
        isDataLoaded={slurmDataLoaded}
        contexts={slurmClusters}
        gpus={allSlurmGPUs}
        groupedPerContextGPUs={groupedPerClusterSlurmGPUs}
        groupedPerNodeGPUs={groupedPerNodeSlurmGPUs}
        handleContextClick={handleContextClick}
        contextStats={contextStats}
        jobsData={sshAndKubeJobsData}
        isJobsDataLoading={sshAndKubeJobsDataLoading}
        isClusterDataLoading={clusterDataLoading}
        isSSH={false}
        isSlurm={true}
        contextWorkspaceMap={{}}
        isInitialLoad={isInitialLoad}
        statusByKey={extraStatusByKey}
      />
    );
  };

  const renderKubernetesTab = () => {
    // If a context is selected, show its details immediately. Don't gate
    // on kubeLoading — the page-level fetch can take 5-10s on tenants
    // with many contexts (some failing K8s API calls), and gating the
    // entire detail view behind it makes plugin-contributed content
    // (status panels, etc.) wait for OSS data they don't depend on.
    // ContextDetails handles empty gpus/nodes arrays gracefully; OSS
    // sub-sections render their own skeletons while data loads.
    if (selectedContext) {
      return renderContextDetails(selectedContext);
    }

    // Dynamically determine section order based on current data availability
    // Sections will reorder automatically as data becomes ready
    const sections = [];

    // Helper function to check if contexts have activity
    const hasContextActivity = (contexts, isSSH = false) => {
      return contexts.some((context) => {
        const contextKey = isSSH
          ? `ssh/${context.replace(/^ssh-/, '')}`
          : `kubernetes/${context}`;
        const stats = contextStats[contextKey] || { clusters: 0, jobs: 0 };
        return stats.clusters > 0 || stats.jobs > 0;
      });
    };

    // If all infrastructure is disabled, show ONLY the empty-state hint —
    // hide the per-type cards (which would all be empty anyway). Plugins can
    // replace the default OSS hint via the `infra.emptyState` slot (e.g. to
    // show a richer "Connect your first infrastructure" CTA).
    if (allInfrastructureDisabled) {
      sections.push({
        name: 'Infrastructure Hint',
        render: () => (
          <PluginSlot
            name="infra.emptyState"
            fallback={<InfrastructureHint />}
          />
        ),
        hasActivity: false,
        priority: 0, // Highest priority, always show at the top
      });
    } else {
      // Add per-type sections (each handles its own loading/empty states).

      // Add Kubernetes section (always show) - Priority 1 to show at top
      // Kubernetes section is active if there are any contexts available (similar to Cloud logic)
      const kubeHasActivity = kubeContexts.length > 0;
      sections.push({
        name: 'Kubernetes',
        render: renderKubernetesInfrastructure,
        hasActivity: kubeHasActivity,
        priority: 1, // Kubernetes gets priority 1 within same activity level
      });

      // Add Slurm section (always show)
      const slurmHasActivity = slurmClusters.length > 0;
      sections.push({
        name: 'Slurm',
        render: renderSlurmInfrastructure,
        hasActivity: slurmHasActivity,
        priority: 2, // Slurm gets priority 2 within same activity level
      });

      // Add Cloud section (always show)
      // Cloud section is active if there are any enabled clouds or
      // storage-only cloud rows.
      const cloudHasActivity = filteredEnabledCloudsCount > 0;
      sections.push({
        name: 'Cloud',
        render: renderCloudInfrastructure,
        hasActivity: cloudHasActivity,
        priority: 3, // Cloud gets priority 3 within same activity level
      });

      // Add SSH section (always show)
      const sshHasActivity = sshContexts.length > 0;
      sections.push({
        name: 'SSH Node Pool',
        render: renderSSHNodePoolInfrastructure,
        hasActivity: sshHasActivity,
        priority: 4, // SSH gets priority 4 within same activity level
      });
    }

    // Dynamic sorting: enabled/active sections move to front automatically
    // This re-sorts every render as data becomes available
    const sortedSections = sections.sort((a, b) => {
      // Primary sort: active sections come first (this causes dynamic reordering)
      if (a.hasActivity !== b.hasActivity) {
        return a.hasActivity ? -1 : 1; // active sections move to front
      }
      // Secondary sort: maintain consistent order within same activity level
      return a.priority - b.priority;
    });

    return (
      <>
        {sortedSections.map((section, index) => (
          <React.Fragment key={index}>{section.render()}</React.Fragment>
        ))}
      </>
    );
  };

  // Check if K8s context node info is still loading (Phase 2 progressive loading)
  const isKubeContextsLoading =
    allKubeContextNames.length > 0 &&
    loadedContexts.size < allKubeContextNames.length;

  // Check if any data is currently loading (all panels and subcomponents).
  // Plugin-contributed rows count toward "any loading" so Refresh disables
  // and the indicator stays visible until plugin data resolves too.
  const isAnyLoading =
    kubeLoading ||
    cloudLoading ||
    slurmLoading ||
    sshAndKubeJobsDataLoading ||
    clusterDataLoading ||
    isKubeContextsLoading ||
    isFetching ||
    (hasInfraExtension && pluginInfraLoading);

  // Check if all data has been loaded at least once
  const isAllDataLoaded =
    kubeDataLoaded && cloudDataLoaded && slurmDataLoaded && !isInitialLoad;

  // Update lastFetchedTime when loading completes (transitions from loading to not loading)
  useEffect(() => {
    if (wasLoadingRef.current && !isAnyLoading) {
      // Loading just completed
      setLastFetchedTime(new Date());
    }
    wasLoadingRef.current = isAnyLoading;
  }, [isAnyLoading]);

  return (
    <>
      {/* One loader component per registered data-provider that exposes
          `useExtraInfraRows`. Each loader owns its own hook calls; the
          plugin's hook count never affects GPUs's hook count. */}
      {extraInfraProviders.map((p) => (
        <ProviderInfraRowsLoader
          key={p.id}
          providerId={p.id}
          useHook={p.hooks.useExtraInfraRows}
          onResult={recordExtraInfraResult}
        />
      ))}
      {selectedContext && (
        // Detail-view header: small back button on its own line, then a
        // larger h1 row below (rendered further down). This matches the
        // dashboard's other detail pages and gives the leaf identifier
        // proper visual weight.
        <div className="mb-2">
          <Link
            href="/infra"
            className="inline-flex items-center gap-1 text-sm text-gray-500 hover:text-gray-700 cursor-pointer"
          >
            ← Infrastructure
          </Link>
        </div>
      )}
      {/* List-view top bar: title link + workspace selector + Refresh +
          plugin header actions. Skipped entirely on a detail page —
          the back link above already serves as the leaf navigation,
          and the page-level Refresh / Add Infra controls don't apply
          when viewing one infra. Hiding the whole row also closes the
          ~36px gap (h-5 + mb-4) between the back link and the h1. */}
      {!selectedContext && (
        <div className="flex items-center justify-between mb-4 h-5">
          <div className="text-base flex items-center">
            <Link href="/infra" className="text-sky-blue cursor-default">
              Infrastructure
            </Link>
          </div>
          <div className="flex items-center">
            {/* Workspace Selector */}
            {availableWorkspaces.length > 0 && (
              <div className="flex items-center mr-4">
                <label className="text-sm font-medium text-gray-700 mr-2">
                  Workspace:
                </label>
                <Select
                  value={selectedWorkspace}
                  onValueChange={setSelectedWorkspace}
                >
                  <SelectTrigger className="w-40 h-8 text-sm">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All Workspaces</SelectItem>
                    {availableWorkspaces.map((workspace) => (
                      <SelectItem key={workspace} value={workspace}>
                        {workspace}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            )}

            {isAnyLoading && (
              <div className="flex items-center mr-2">
                <CircularProgress size={15} className="mt-0" />
                <span className="ml-2 text-gray-500">Loading...</span>
              </div>
            )}
            {!isAnyLoading && lastFetchedTime && (
              <LastUpdatedTimestamp
                timestamp={lastFetchedTime}
                className="mr-2"
              />
            )}
            <button
              onClick={handleRefresh}
              disabled={isAnyLoading}
              className="text-sky-blue hover:text-sky-blue-bright flex items-center"
            >
              <RotateCwIcon className="h-4 w-4 mr-1.5" />
              {!isMobile && 'Refresh'}
            </button>
            <PluginSlot name="infra.headerActions" wrapperClassName="ml-3" />
          </div>
        </div>
      )}

      <PluginSlot name="infra.attentionBanner" />

      {selectedContext && (
        // Large h1 title + plugin-injected header actions (e.g. Remove)
        // on a single row.
        <div className="flex items-center justify-between gap-3 mb-5">
          <h1
            className={`text-2xl font-semibold text-gray-900 leading-tight tracking-tight ${
              selectedContext.startsWith('ssh-') ||
              slurmClusters.includes(selectedContext)
                ? ''
                : 'font-mono'
            }`}
          >
            {selectedContext.startsWith('ssh-')
              ? selectedContext.replace(/^ssh-/, '')
              : selectedContext}
          </h1>
          <PluginSlot
            name="infra.contextDetail.headerActions"
            context={{
              contextName: selectedContext.startsWith('ssh-')
                ? selectedContext.replace(/^ssh-/, '')
                : selectedContext,
              isSlurm: slurmClusters.includes(selectedContext),
              isSsh: selectedContext.startsWith('ssh-'),
            }}
            wrapperClassName="flex items-center gap-2"
          />
        </div>
      )}

      {/* Each section handles its own loading state */}
      {renderKubernetesTab()}

      {/* SSH Node Pool Modal - Always available */}
      <SSHNodePoolModal
        isOpen={sshModalOpen}
        onClose={() => setSshModalOpen(false)}
        onSave={handleSaveSSHPool}
        poolData={editingPool}
        isLoading={sshLoading}
      />
    </>
  );
}

// Renders nothing, but calls a plugin-provided custom hook in its own
// component scope. This isolates the plugin's hook calls from the parent
// page's render — so adding/removing data providers doesn't change the
// number of hooks called per parent render (which would be a Rules-of-
// Hooks violation). Used by GPUs to enumerate `useExtraInfraRows`
// hooks contributed by plugin data providers.
//
// The effect MUST depend on `result` (not run on every render) — otherwise
// any plugin hook that returns a fresh object literal each render will
// re-fire onResult forever, the parent re-renders, and the page stalls.
function ProviderInfraRowsLoader({ providerId, useHook, onResult }) {
  const result = useHook();
  React.useEffect(() => {
    onResult(providerId, result);
  }, [providerId, result, onResult]);
  return null;
}

// Helper table component for cloud GPUs
function CloudGpuTable({ data, title }) {
  const [currentPage, setCurrentPage] = React.useState(1);
  const [pageSize, setPageSize] = React.useState(10);

  // Add defensive check for data
  const safeData = data || [];

  if (safeData.length === 0) {
    return (
      <>
        <h3 className="text-lg font-semibold mb-3">{title}</h3>
        <p className="text-sm text-gray-500">
          No GPUs found for this category.
        </p>
      </>
    );
  }

  const totalPages = Math.ceil(safeData.length / pageSize);
  const startIndex = (currentPage - 1) * pageSize;
  const endIndex = Math.min(startIndex + pageSize, safeData.length);
  const paginatedData = safeData.slice(startIndex, endIndex);

  const goToPreviousPage = () => {
    setCurrentPage((page) => Math.max(page - 1, 1));
  };
  const goToNextPage = () => {
    setCurrentPage((page) => Math.min(page + 1, totalPages));
  };
  const handlePageSizeChange = (e) => {
    const newSize = parseInt(e.target.value, 10);
    setPageSize(newSize);
    setCurrentPage(1); // Reset to first page when page size changes
  };

  return (
    <>
      <h3 className="text-lg font-semibold mb-3">{title}</h3>
      <div className="overflow-x-auto">
        <table className="min-w-full text-sm border-b border-gray-200">
          <thead className="bg-gray-100">
            <tr>
              <th className="p-2 text-left font-medium text-gray-600">GPU</th>
              <th className="p-2 text-left font-medium text-gray-600">
                Available Quantities / Node
              </th>
            </tr>
          </thead>
          <tbody className="bg-white divide-y divide-gray-200">
            {paginatedData.map((gpu, idx) => (
              <tr key={`${gpu.gpu_name}-${idx}`}>
                <td className="p-2 whitespace-nowrap text-gray-700">
                  {canonicalizeGpuName(gpu.gpu_name)}
                </td>
                <td className="p-2 whitespace-nowrap text-gray-700">
                  {gpu.gpu_quantities}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      {/* Pagination controls */}
      {safeData.length > pageSize && (
        <div className="flex justify-end items-center py-2 px-4 text-sm text-gray-700">
          <div className="flex items-center space-x-4">
            <div className="flex items-center">
              <span className="mr-2">Rows per page:</span>
              <div className="relative inline-block">
                <select
                  value={pageSize}
                  onChange={handlePageSizeChange}
                  className="py-1 pl-2 pr-6 appearance-none outline-none cursor-pointer border-none bg-transparent"
                  style={{ minWidth: '40px' }}
                >
                  <option value={10}>10</option>
                  <option value={25}>25</option>
                  <option value={50}>50</option>
                  <option value={100}>100</option>
                </select>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-4 w-4 text-gray-500 absolute right-0 top-1/2 transform -translate-y-1/2 pointer-events-none"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M19 9l-7 7-7-7"
                  />
                </svg>
              </div>
            </div>
            <div>
              {startIndex + 1} – {endIndex} of {safeData.length}
            </div>
            <div className="flex items-center space-x-2">
              <button
                className="p-1 rounded-full hover:bg-gray-200 disabled:opacity-30 disabled:hover:bg-transparent"
                onClick={goToPreviousPage}
                disabled={currentPage === 1}
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="16"
                  height="16"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M15 18l-6-6 6-6" />
                </svg>
              </button>
              <button
                className="p-1 rounded-full hover:bg-gray-200 disabled:opacity-30 disabled:hover:bg-transparent"
                onClick={goToNextPage}
                disabled={currentPage === totalPages || totalPages === 0}
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="16"
                  height="16"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M9 18l6-6-6-6" />
                </svg>
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
